<#
.SYNOPSIS
    vCenter discovery automation with Serbian language.
.DESCRIPTION
    vCenter otkrivanje sa srpskim jezikom i integracijom sa utility framework-om.
.PARAMETER Config
    Konfiguracioni objekat
.PARAMETER SpecificClusters
    Specifični klasteri
.PARAMETER IncludeVMs
    Uključi VM-ove
.PARAMETER ExportResults
    Izvezi rezultate
.EXAMPLE
    Invoke-vCenterDiscovery -Config $config
.NOTES
    File Name      : 06_Discovery_vCenter.ps1
    Author         : Generated by Opencode
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

# Import utility functions
. "$PSScriptRoot\..\05_Utility\ConnectionManager.ps1"
. "$PSScriptRoot\..\05_Utility\ErrorHandler.ps1"
. "$PSScriptRoot\..\05_Utility\Logger.ps1"
. "$PSScriptRoot\..\05_Utility\ConfigManager.ps1"

function Invoke-vCenterDiscovery {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$false)]
        [string[]]$SpecificClusters = @(),
        
        [Parameter(Mandatory=$false)]
        [switch]$IncludeVMs = $true,
        
        [Parameter(Mandatory=$false)]
        [switch]$ExportResults = $true
    )
    
    $discoveryResult = $null
    
    Try-CatchBlock -Context "vCenter Discovery" -RecoveryActions @(
        (New-RecoveryAction -Action {
            param($ErrorInfo)
            Write-EnhancedLog "Pokušaj re-konekcije na vCenter..." "INFO" "Discovery"
            $connection = Connect-vCenterSafely -Server $Config.vCenter.server -Credential (Get-StoredCredential -Target $Config.vCenter.credentialTarget)
            return @{ Success = $true; Connection = $connection }
        } -Name "Reconnect-vCenter" -MaxAttempts 3)
    ) -FinallyBlock {
        if ($script:vCenterConnections) {
            Disconnect-AllSafely
        }
    } -ScriptBlock {
        
        Write-EnhancedLog "Povezivanje na vCenter: $($Config.vCenter.server)" "INFO" "Discovery"
        $connection = Connect-vCenterSafely -Server $Config.vCenter.server -Credential (Get-StoredCredential -Target $Config.vCenter.credentialTarget) -TestConnection
        
        Write-EnhancedLog "Prikupljanje podataka o vCenter infrastrukturi..." "INFO" "Discovery"
        
        $discoveryData = [PSCustomObject]@{
            Timestamp = Get-Date
            vCenterServer = $Config.vCenter.server
            Datacenters = Get-Datacenter -Server $connection | Select-Object Name, Id
            Clusters = @()
            Hosts = @()
            VMs = @()
            Datastores = @()
            Networks = @()
            Summary = @{}
        }
        
        # Get clusters
        if ($SpecificClusters.Count -gt 0) {
            $discoveryData.Clusters = Get-Cluster -Server $connection -Name $SpecificClusters
        } else {
            $discoveryData.Clusters = Get-Cluster -Server $connection
        }
        
        # Get hosts for each cluster
        foreach ($cluster in $discoveryData.Clusters) {
            $hosts = Get-VMHost -Server $connection -Location $cluster
            $discoveryData.Hosts += $hosts | Select-Object Name, PowerState, ConnectionState, NumCpu, MemoryUsageGB
        }
        
        # Get VMs if requested
        if ($IncludeVMs) {
            $discoveryData.VMs = Get-VM -Server $connection | Select-Object Name, PowerState, Guest, NumCpu, MemoryGB
        }
        
        # Create summary
        $discoveryData.Summary = [PSCustomObject]@{
            TotalClusters = $discoveryData.Clusters.Count
            TotalHosts = $discoveryData.Hosts.Count
            TotalVMs = $discoveryData.VMs.Count
            TotalDatastores = $discoveryData.Datastores.Count
            TotalNetworks = $discoveryData.Networks.Count
        }
        
        Write-EnhancedLog "Otkriveno resursa: $($discoveryData.Summary.TotalClusters) klastera, $($discoveryData.Summary.TotalHosts) hostova, $($discoveryData.Summary.TotalVMs) VM-ova" "SUCCESS" "Discovery"
        
        return $discoveryData
    }
    
    return $discoveryResult
}

# Export funkcije
Export-ModuleMember -Function Invoke-vCenterDiscovery
