version: '3'

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.9.0
    hostname: wazuh-indexer
    container_name: wazuh-indexer
    restart: always
    ports:
      - "9200:9200"
    environment:
      - INDEXER_MEMORY="" 
      - "discovery.type=single-node"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - wazuh-indexer-plugins:/usr/share/wazuh-indexer/plugins
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - wazuh-tier

  wazuh-manager:
    image: wazuh/wazuh-manager:4.9.0
    hostname: wazuh-manager
    container_name: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "1516:1516"
    environment:
      - INDEXER_HOST=wazuh-indexer
      - FILEBEAT_ENABLED=true
      - FILEBEAT_SSL_VERIFICATION_MODE="full"
      - ELASTICSEARCH_URL=https://wazuh-indexer:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=admin
      - SSL_CERTIFICATE_AUTHORITY=""
      - SSL_CERTIFICATE="/etc/sslslinner/wazuh-manager/Wazuh-OSSG3R3C4S3G4U.crt"
      - SSL_KEY="/etc/sslslinner/wazuh-manager/Wazuh-OSSG3R3C4S3G4U.key"
    volumes:
      - wazuh-manager-configuration:/var/ossec/data/configuration
      - wazuh-manager-logs:/var/ossec/logs
      - wazuh-manager-etc:/var/ossec/etc
      - wazuh-manager-integrations:/var/ossec/integrations
      - wazuh-manager-active-response:/var/ossec/active-response
      - wazuh-manager-agentless:/var/ossec/agentless
      - wazuh-manager-wodles:/var/ossec/wodles
      - wazuh-agent-authd:/var/ossecagent-authd
    networks:
      - wazuh-tier

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.9.0
    hostname: wazuh-dashboard
    container_name: wazuh-dashboard
    restart: always
    ports:
      - "443:443"
    environment:
      - INDEXER_HOST=wazuh-indexer
      - DASHBOARD_MEMORY=""
      - WAZUH_URL=http://wazuh-manager
      - WAZUH_USERNAME=admin
      - WAZUH_PASSWORD=admin
    volumes:
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
    networks:
      - wazuh-tier

networks:
  wazuh-tier:
    driver: bridge

volumes:
  wazuh-indexer-data:
  wazuh-indexer-plugins:
  wazuh-manager-configuration:
  wazuh-manager-logs:
  wazuh-manager-etc:
  wazuh-manager-integrations:
  wazuh-manager-active-response:
  wazuh-manager-agentless:
  wazuh-manager-wodles:
  wazuh-agent-authd:
  wazuh-dashboard-config: