<#
.SYNOPSIS
    vSphere maintenance mode automation with Serbian language.
.DESCRIPTION
    Automatizovano upravljanje maintenance mode za vSphere hostove.
.PARAMETER Config
    Konfiguracioni objekat
.PARAMETER TargetHosts
    Lista ciljnih hostova
.PARAMETER Action
    Akcija: Enter, Exit, Status
.PARAMETER EvacuateVMs
    Evakuacija VM-ova pri ulasku u maintenance mode
.EXAMPLE
    Invoke-MaintenanceMode -Config $config -Action Enter -EvacuateVMs
.NOTES
    File Name      : 11_Maintenance_Mode.ps1
    Author         : Generated by Opencode
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

# Import utility functions
. "$PSScriptRoot\..\05_Utility\ConnectionManager.ps1"
. "$PSScriptRoot\..\05_Utility\ErrorHandler.ps1"
. "$PSScriptRoot\..\05_Utility\Logger.ps1"
. "$PSScriptRoot\..\05_Utility\ConfigManager.ps1"

function Invoke-MaintenanceMode {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$false)]
        [string[]]$TargetHosts = @(),
        
        [Parameter(Mandatory=$true)]
        [ValidateSet("Enter", "Exit", "Status")]
        [string]$Action,
        
        [Parameter(Mandatory=$false)]
        [switch]$EvacuateVMs = $true,
        
        [Parameter(Mandatory=$false)]
        [switch]$ParallelExecution = $false,
        
        [Parameter(Mandatory=$false)]
        [int]$vMotionTimeout = 60
    )
    
    Try-CatchBlock -Context "Maintenance Mode Operations" -RecoveryActions @(
        (New-RecoveryAction -Action {
            param($ErrorInfo)
            Write-EnhancedLog "Pokušaj re-konekcije na vCenter..." "INFO" "MaintenanceMode"
            $connection = Connect-vCenterSafely -Server $Config.vCenter.server -Credential (Get-StoredCredential -Target $Config.vCenter.credentialTarget)
            return @{ Success = $true; Connection = $connection }
        } -Name "Reconnect-vCenter" -MaxAttempts 3)
    ) -FinallyBlock {
        Disconnect-AllSafely
    } -ScriptBlock {
        
        Write-EnhancedLog "=== POČETAK MAINTENANCE MODE OPERACIJA ===" "SUCCESS" "MaintenanceMode"
        Write-EnhancedLog "Akcija: $Action" "INFO" "MaintenanceMode"
        Write-EnhancedLog "Evakuacija VM-ova: $EvacuateVMs" "INFO" "MaintenanceMode"
        
        # Connect to vCenter
        $vCenterConnection = Connect-vCenterSafely -Server $Config.vCenter.server -Credential (Get-StoredCredential -Target $Config.vCenter.credentialTarget) -TestConnection
        
        # Get target hosts if not specified
        if ($TargetHosts.Count -eq 0) {
            $clusterHosts = Get-Cluster -Name $Config.vCenter.clusterName -Server $vCenterConnection | Get-VMHost
            $TargetHosts = $clusterHosts.Name
        }
        
        $operationResults = @()
        
        foreach ($hostName in $TargetHosts) {
            $hostResult = Invoke-MaintenanceModeHost -HostName $hostName -Action $Action -EvacuateVMs:$EvacuateVMs -vMotionTimeout $vMotionTimeout -Config $Config
            $operationResults += $hostResult
        }
        
        $summary = [PSCustomObject]@{
            Action = $Action
            TotalHosts = $TargetHosts.Count
            SuccessfulOperations = ($operationResults | Where-Object { $_.Status -eq "Success" }).Count
            FailedOperations = ($operationResults | Where-Object { $_.Status -in @("Failed", "Error") }).Count
            HostResults = $operationResults
            StartTime = Get-Date
            EndTime = Get-Date
            EvacuateVMsEnabled = $EvacuateVMs
            ParallelExecution = $ParallelExecution
        }
        
        Write-EnhancedLog "=== MAINTENANCE MODE OPERACIJE ZAVRŠENE ===" "SUCCESS" "MaintenanceMode"
        
        return $summary
    }
}

function Invoke-MaintenanceModeHost {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$HostName,
        
        [Parameter(Mandatory=$true)]
        [string]$Action,
        
        [Parameter(Mandatory=$false)]
        [switch]$EvacuateVMs,
        
        [Parameter(Mandatory=$false)]
        [int]$vMotionTimeout = 60,
        
        [Parameter(Mandatory=$true)]
        [object]$Config
    )
    
    try {
        Write-EnhancedLog "Obrada hosta: $HostName (Akcija: $Action)" "INFO" "MaintenanceMode"
        
        # Get VMHost object
        $vmHost = Get-VMHost -Name $HostName -ErrorAction Stop
        $hostResult = [PSCustomObject]@{
            HostName = $HostName
            Action = $Action
            Status = "Processed"
            Message = "Maintenance mode operation completed"
            VMCount = 0
            VMMigratedCount = 0
            StartTime = Get-Date
            EndTime = $null
            Duration = 0
        }
        
        switch ($Action) {
            "Enter" {
                # Enter maintenance mode logic
                Write-EnhancedLog "Ulazak u maintenance mode za $HostName..." "INFO" "MaintenanceMode"
                Set-VMHost -VMHost $vmHost -State "Maintenance" -ErrorAction Stop
                $hostResult.Message = "Uspešno ulazak u maintenance mode"
            }
            "Exit" {
                # Exit maintenance mode logic
                Write-EnhancedLog "Izlazak iz maintenance mode za $HostName..." "INFO" "MaintenanceMode"
                Set-VMHost -VMHost $vmHost -State "Connected" -ErrorAction Stop
                $hostResult.Message = "Uspešno izlazak iz maintenance mode"
            }
            "Status" {
                $currentMaintenanceMode = $vmHost.ConnectionState -eq "Maintenance"
                $hostResult.Message = if ($currentMaintenanceMode) { "U maintenance mode" } else { "Van maintenance mode" }
            }
        }
        
    } catch {
        $hostResult.Status = "Failed"
        $hostResult.Message = "Greška: $($_.Exception.Message)"
    }
    
    $hostResult.EndTime = Get-Date
    $hostResult.Duration = ($hostResult.EndTime - $hostResult.StartTime).TotalMinutes
    
    return $hostResult
}

# Export funkcije
Export-ModuleMember -Function Invoke-MaintenanceMode, Invoke-MaintenanceModeHost
