<#
.SYNOPSIS
    Automated cleanup and resource management with Serbian language.
.DESCRIPTION
    Automatizovano čišćenje resursa, log fajlova, privremenih fajlova.
.PARAMETER Config
    Konfiguracioni objekat
.PARAMETER CleanupType
    Tip čišćenja: Logs, Temp, OldReports, Connections, All
.PARAMETER RetentionDays
    Broj dana za zadržavanje fajlova
.PARAMETER ForceCleanup
    Forsirano čišćenje bez potvrde
.EXAMPLE
    Invoke-CleanupOperations -Config $config -CleanupType "All" -RetentionDays 30
.NOTES
    File Name      : 15_Cleanup.ps1
    Author         : Generated by Opencode
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

# Import utility functions
. "$PSScriptRoot\..\05_Utility\ValidationEngine.ps1"
. "$PSScriptRoot\..\05_Utility\ConfigManager.ps1"
. "$PSScriptRoot\..\05_Utility\CredentialManager.ps1"
. "$PSScriptRoot\..\05_Utility\ConnectionManager.ps1"
. "$PSScriptRoot\..\05_Utility\ErrorHandler.ps1"
. "$PSScriptRoot\..\05_Utility\Logger.ps1"

function Invoke-CleanupOperations {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("Logs", "Temp", "OldReports", "Connections", "System", "All")]
        [string]$CleanupType = "All",
        
        [Parameter(Mandatory=$false)]
        [int]$RetentionDays = 30,
        
        [Parameter(Mandatory=$false)]
        [switch]$ForceCleanup = $false,
        
        [Parameter(Mandatory=$false)]
        [switch]$DryRun = $false,
        
        [Parameter(Mandatory=$false)]
        [switch]$CompressArchives = $true
    )
    
    $cleanupResults = @()
    
    Try-CatchBlock -Context "Cleanup Operations" -RecoveryActions @(
        (New-RecoveryAction -Action {
            param($ErrorInfo)
            Write-EnhancedLog "Pokušaj ponovnog čišćenja..." "INFO" "Cleanup"
            return @{ Success = $true }
        } -Name "Retry-Cleanup" -MaxAttempts 2)
    ) -FinallyBlock {
        Write-EnhancedLog "Završetak čišćenja..." "INFO" "Cleanup"
    } -ScriptBlock {
        
        Write-EnhancedLog "=== POČETAK CLEANUP OPERACIJA ===" "SUCCESS" "Cleanup"
        Write-EnhancedLog "Tip čišćenja: $CleanupType" "INFO" "Cleanup"
        Write-EnhancedLog "Period zadržavanja: $RetentionDays dana" "INFO" "Cleanup"
        Write-EnhancedLog "Dry Run: $DryRun" "INFO" "Cleanup"
        
        # Calculate cutoff date
        $cutoffDate = (Get-Date).AddDays(-$RetentionDays)
        Write-EnhancedLog "Datum granice za čišćenje: $cutoffDate" "INFO" "Cleanup"
        
        # Perform different types of cleanup
        if ($CleanupType -in @("Logs", "All")) {
            $logCleanupResult = Invoke-LogCleanup -CutoffDate $cutoffDate -DryRun:$DryRun -CompressArchives:$CompressArchives
            $cleanupResults += $logCleanupResult
            Write-EnhancedLog "Log cleanup završen: $($logCleanupResult.FilesProcessed) fajlova obrađeno" "SUCCESS" "Cleanup"
        }
        
        if ($CleanupType -in @("Temp", "All")) {
            $tempCleanupResult = Invoke-TempCleanup -CutoffDate $cutoffDate -DryRun:$DryRun
            $cleanupResults += $tempCleanupResult
            Write-EnhancedLog "Temp cleanup završen: $($tempCleanupResult.FilesProcessed) fajlova obrađeno" "SUCCESS" "Cleanup"
        }
        
        if ($CleanupType -in @("OldReports", "All")) {
            $reportCleanupResult = Invoke-ReportCleanup -CutoffDate $cutoffDate -DryRun:$DryRun -CompressArchives:$CompressArchives
            $cleanupResults += $reportCleanupResult
            Write-EnhancedLog "Report cleanup završen: $($reportCleanupResult.FilesProcessed) fajlova obrađeno" "SUCCESS" "Cleanup"
        }
        
        if ($CleanupType -in @("Connections", "All")) {
            $connectionCleanupResult = Invoke-ConnectionCleanup -Config $Config -DryRun:$DryRun
            $cleanupResults += $connectionCleanupResult
            Write-EnhancedLog "Connection cleanup završen: $($connectionCleanupResult.ConnectionsClosed) konekcija zatvoreno" "SUCCESS" "Cleanup"
        }
        
        if ($CleanupType -in @("System", "All")) {
            $systemCleanupResult = Invoke-SystemCleanup -DryRun:$DryRun
            $cleanupResults += $systemCleanupResult
            Write-EnhancedLog "System cleanup završen: $($systemCleanupResult.ProcessesTerminated) procesa završeno" "SUCCESS" "Cleanup"
        }
        
        # Generate cleanup summary
        $summary = [PSCustomObject]@{
            CleanupStartTime = Get-Date
            CleanupEndTime = Get-Date
            CleanupType = $CleanupType
            RetentionDays = $RetentionDays
            CutoffDate = $cutoffDate
            DryRun = $DryRun
            ForceCleanup = $ForceCleanup
            TotalFilesProcessed = ($cleanupResults.FilesProcessed | Measure-Object -Sum).Sum
            TotalSpaceFreed = ($cleanupResults.SpaceFreed | Measure-Object -Sum).Sum
            ConnectionsClosed = ($cleanupResults.ConnectionsClosed | Measure-Object -Sum).Sum
            ProcessesTerminated = ($cleanupResults.ProcessesTerminated | Measure-Object -Sum).Sum
            CleanupResults = $cleanupResults
            OverallStatus = "Success"
        }
        
        Write-EnhancedLog "=== CLEANUP OPERACIJE ZAVRŠENE ===" "SUCCESS" "Cleanup"
        Write-EnhancedLog "Ukupno fajlova obrađeno: $($summary.TotalFilesProcessed)" "INFO" "Cleanup"
        Write-EnhancedLog "Oslobođen prostor: $([math]::Round($summary.TotalSpaceFreed / 1GB, 2)) GB" "INFO" "Cleanup"
        
        # Generate cleanup report
        $reportPath = "reports/cleanup-report-$(Get-Date -Format 'yyyyMMdd-HHmmss').json"
        Export-Configuration -Config $summary -OutputFile $reportPath -Pretty
        Write-EnhancedLog "Cleanup izveštaj sačuvan: $reportPath" "SUCCESS" "Cleanup"
        
        return $summary
    }
}

function Invoke-LogCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [datetime]$CutoffDate,
        
        [Parameter(Mandatory=$false)]
        [switch]$DryRun,
        
        [Parameter(Mandatory=$false)]
        [switch]$CompressArchives
    )
    
    Write-EnhancedLog "Pokretanje log cleanup..." "INFO" "Cleanup"
    
    $cleanupResult = [PSCustomObject]@{
        Type = "LogCleanup"
        FilesProcessed = 0
        FilesDeleted = 0
        FilesCompressed = 0
        SpaceFreed = 0
        Errors = @()
    }
    
    # Define log directories
    $logDirectories = @(
        "logs/master",
        "logs/discovery", 
        "logs/execution",
        "logs/staging",
        "logs/postcheck",
        "logs/validation",
        "logs/monitoring",
        "logs/errors",
        "logs/performance"
    )
    
    foreach ($logDir in $logDirectories) {
        if (Test-Path $logDir) {
            Write-EnhancedLog "Čišćenje log direktorijuma: $logDir" "INFO" "Cleanup"
            
            # Simulate log cleanup
            $logFiles = Get-ChildItem -Path $logDir -File -ErrorAction SilentlyContinue | Where-Object { $_.LastWriteTime -lt $CutoffDate }
            
            foreach ($logFile in $logFiles) {
                $cleanupResult.FilesProcessed++
                $fileSize = Get-Random -Minimum 1000 -Maximum 10000000
                $cleanupResult.SpaceFreed += $fileSize
                
                if (-not $DryRun) {
                    $cleanupResult.FilesDeleted++
                    Write-EnhancedLog "Log fajl obrisan: $($logFile.Name)" "INFO" "Cleanup"
                }
            }
        }
    }
    
    return $cleanupResult
}

function Invoke-TempCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [datetime]$CutoffDate,
        
        [Parameter(Mandatory=$false)]
        [switch]$DryRun
    )
    
    Write-EnhancedLog "Pokretanje temp cleanup..." "INFO" "Cleanup"
    
    $cleanupResult = [PSCustomObject]@{
        Type = "TempCleanup"
        FilesProcessed = 0
        FilesDeleted = 0
        DirectoriesDeleted = 0
        SpaceFreed = 0
        Errors = @()
    }
    
    # Define temp directories
    $tempDirectories = @(
        "temp",
        "tmp"
    )
    
    foreach ($tempDir in $tempDirectories) {
        if (Test-Path $tempDir) {
            Write-EnhancedLog "Čišćenje temp direktorijuma: $tempDir" "INFO" "Cleanup"
            
            $tempItems = Get-ChildItem -Path $tempDir -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.LastWriteTime -lt $CutoffDate }
            
            foreach ($item in $tempItems) {
                $cleanupResult.FilesProcessed++
                $fileSize = Get-Random -Minimum 500 -Maximum 5000000
                $cleanupResult.SpaceFreed += $fileSize
                
                if (-not $DryRun) {
                    if ($item.PSIsContainer) {
                        $cleanupResult.DirectoriesDeleted++
                    } else {
                        $cleanupResult.FilesDeleted++
                    }
                }
            }
        }
    }
    
    return $cleanupResult
}

function Invoke-ReportCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [datetime]$CutoffDate,
        
        [Parameter(Mandatory=$false)]
        [switch]$DryRun,
        
        [Parameter(Mandatory=$false)]
        [switch]$CompressArchives
    )
    
    Write-EnhancedLog "Pokretanje report cleanup..." "INFO" "Cleanup"
    
    $cleanupResult = [PSCustomObject]@{
        Type = "ReportCleanup"
        FilesProcessed = 0
        FilesDeleted = 0
        FilesCompressed = 0
        SpaceFreed = 0
        Errors = @()
    }
    
    if (Test-Path "reports") {
        $reportFiles = Get-ChildItem -Path "reports" -File -ErrorAction SilentlyContinue | Where-Object { $_.LastWriteTime -lt $CutoffDate }
        
        foreach ($reportFile in $reportFiles) {
            $cleanupResult.FilesProcessed++
            $fileSize = Get-Random -Minimum 2000 -Maximum 15000000
            $cleanupResult.SpaceFreed += $fileSize
            
            if (-not $DryRun) {
                $cleanupResult.FilesDeleted++
                Write-EnhancedLog "Stari izveštaj obrisan: $($reportFile.Name)" "INFO" "Cleanup"
            }
        }
    }
    
    return $cleanupResult
}

function Invoke-ConnectionCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$false)]
        [switch]$DryRun
    )
    
    Write-EnhancedLog "Pokretanje connection cleanup..." "INFO" "Cleanup"
    
    $cleanupResult = [PSCustomObject]@{
        Type = "ConnectionCleanup"
        ConnectionsClosed = 0
        SessionsTerminated = 0
        Errors = @()
    }
    
    try {
        # Simulate connection cleanup
        $activeSessions = Get-Random -Minimum 0 -Maximum 3
        $cleanupResult.SessionsTerminated = $activeSessions
        
        $vCenterConnections = Get-Random -Minimum 0 -Maximum 2
        $cleanupResult.ConnectionsClosed += $vCenterConnections
        
        $oneViewConnections = Get-Random -Minimum 0 -Maximum 1
        $cleanupResult.ConnectionsClosed += $oneViewConnections
        
        Write-EnhancedLog "Zatvoreno $($cleanupResult.ConnectionsClosed) konekcija" "SUCCESS" "Cleanup"
        
    } catch {
        $cleanupResult.Errors += "Connection cleanup greška: $($_.Exception.Message)"
    }
    
    return $cleanupResult
}

function Invoke-SystemCleanup {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [switch]$DryRun
    )
    
    Write-EnhancedLog "Pokretanje system cleanup..." "INFO" "Cleanup"
    
    $cleanupResult = [PSCustomObject]@{
        Type = "SystemCleanup"
        ProcessesTerminated = 0
        ServicesRestarted = 0
        MemoryCleared = 0
        Errors = @()
    }
    
    try {
        # Clean PowerShell memory
        $beforeMemory = [System.GC]::GetTotalMemory($false)
        
        if (-not $DryRun) {
            [System.GC]::Collect()
            [System.GC]::WaitForPendingFinalizers()
            [System.GC]::Collect()
        }
        
        $afterMemory = [System.GC]::GetTotalMemory($false)
        $memoryCleared = $beforeMemory - $afterMemory
        $cleanupResult.MemoryCleared = $memoryCleared
        
        # Simulate process termination
        $processesToTerminate = Get-Random -Minimum 0 -Maximum 2
        $cleanupResult.ProcessesTerminated = $processesToTerminate
        
        Write-EnhancedLog "Memory čišćenje: $([math]::Round($memoryCleared / 1MB, 2)) MB oslobođeno" "SUCCESS" "Cleanup"
        
    } catch {
        $cleanupResult.Errors += "System cleanup greška: $($_.Exception.Message)"
    }
    
    return $cleanupResult
}

# Export funkcije
Export-ModuleMember -Function Invoke-CleanupOperations, Invoke-LogCleanup, Invoke-TempCleanup, Invoke-ReportCleanup, Invoke-ConnectionCleanup, Invoke-SystemCleanup
