<#
.SYNOPSIS
    Comprehensive test runner for vSphere OneView automation suite.
.DESCRIPTION
    Executes unit tests, integration tests, and mock API tests for the automation suite.
.PARAMETER TestType
    Type of tests to run: Unit, Integration, Mock, All
.PARAMETER Simulation
    Run tests in simulation mode
.PARAMETER Verbose
    Enable verbose output
.PARAMETER ReportFile
    Path to test report file
.EXAMPLE
    .\RunAllTests.ps1 -TestType All -Verbose
.EXAMPLE
    .\RunAllTests.ps1 -TestType Unit -ReportFile "test-results.json"
.NOTES
    File Name      : RunAllTests.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [ValidateSet('Unit', 'Integration', 'Mock', 'All')]
    [string]$TestType = 'All',
    
    [Parameter(Mandatory=$false)]
    [switch]$Simulation = $true,
    
    [Parameter(Mandatory=$false)]
    [switch]$Verbose,
    
    [Parameter(Mandatory=$false)]
    [string]$ReportFile = "reports/TestResults_$(Get-Date -Format 'yyyyMMdd_HHmm').json"
)

# Import utility functions
. "$PSScriptRoot\..\05_Utility\Logger.ps1"
. "$PSScriptRoot\..\05_Utility\ConfigManager.ps1"

# Initialize
$script:StartTime = Get-Date
$script:Component = "TestRunner"
$script:TestResults = @()
$script:LogFile = "logs/tests/TestRun_$(Get-Date -Format 'yyyyMMdd_HHmm').log"

# Ensure log directory exists
$logDir = Split-Path $script:LogFile -Parent
if (-not (Test-Path $logDir)) {
    New-Item -Path $logDir -ItemType Directory -Force | Out-Null
}

function Write-TestLog {
    param([string]$Message, [string]$Level = "INFO")
    Write-EnhancedLog $Message $Level $script:Component -LogFile $script:LogFile
}

function New-TestResult {
    param(
        [string]$TestName,
        [string]$Category,
        [bool]$Passed,
        [string]$Message = "",
        [timespan]$Duration = [timespan]::Zero,
        [hashtable]$Details = @{}
    )
    
    return [PSCustomObject]@{
        TestName = $TestName
        Category = $Category
        Passed = $Passed
        Message = $Message
        Duration = $Duration.TotalSeconds
        Timestamp = Get-Date
        Details = $Details
    }
}

function Invoke-Test {
    param(
        [string]$TestName,
        [string]$Category,
        [scriptblock]$TestScript,
        [hashtable]$Parameters = @{}
    )
    
    try {
        Write-TestLog "Running test: $TestName" "INFO"
        $testStart = Get-Date
        
        $result = & $TestScript @Parameters
        
        $testEnd = Get-Date
        $duration = $testEnd - $testStart
        
        if ($result -is [bool]) {
            $passed = $result
            $message = if ($passed) { "Test passed" } else { "Test failed" }
        } elseif ($result -is [hashtable] -and $result.ContainsKey('Passed')) {
            $passed = $result.Passed
            $message = if ($passed) { $result.Message } else { $result.Message }
        } else {
            $passed = $false
            $message = "Invalid test result format"
        }
        
        $testResult = New-TestResult -TestName $TestName -Category $Category -Passed $passed -Message $message -Duration $duration -Details $result
        $script:TestResults += $testResult
        
        $status = if ($passed) { "PASSED" } else { "FAILED" }
        Write-TestLog "Test $TestName`: $status" if($passed) { "SUCCESS" } else { "ERROR" }
        
        if ($Verbose) {
            Write-TestLog "Test result details: $($result | ConvertTo-Json -Compress)" "DEBUG"
        }
        
        return $testResult
        
    } catch {
        $testEnd = Get-Date
        $duration = $testEnd - $testStart
        
        $testResult = New-TestResult -TestName $TestName -Category $Category -Passed $false -Message "Test error: $($_.Exception.Message)" -Duration $duration
        $script:TestResults += $testResult
        
        Write-TestLog "Test $TestName`: ERROR - $($_.Exception.Message)" "ERROR"
        
        if ($Verbose) {
            Write-TestLog "Test error details: $($_.Exception.StackTrace)" "DEBUG"
        }
        
        return $testResult
    }
}

function Test-UnitTests {
    Write-TestLog "Running unit tests..." "INFO"
    
    # Test Logger functionality
    Invoke-Test -TestName "Logger Write-EnhancedLog" -Category "Unit" -TestScript {
        $testLogFile = "temp/test.log"
        $testMessage = "Test message"
        Write-EnhancedLog $testMessage "INFO" "TestUnit" -LogFile $testLogFile
        
        $fileContent = Get-Content $testLogFile -Raw
        $passed = $fileContent -contains $testMessage
        
        # Cleanup
        if (Test-Path $testLogFile) {
            Remove-Item $testLogFile -Force
        }
        
        return @{ Passed = $passed; Message = if ($passed) { "Log written successfully" } else { "Log not written" } }
    }
    
    # Test ConfigManager functionality
    Invoke-Test -TestName "ConfigManager Load Configuration" -Category "Unit" -TestScript {
        $testConfigFile = "config/settings.template.json"
        
        if (Test-Path $testConfigFile) {
            $config = Get-Configuration -ConfigFile $testConfigFile -SkipValidation
            $passed = ($null -ne $config -and $config.system.version -eq "1.0.0")
            
            return @{ 
                Passed = $passed; 
                Message = if ($passed) { "Configuration loaded successfully" } else { "Configuration not loaded" }
                Details = @{ Version = if ($config) { $config.system.version } else { $null } }
            }
        } else {
            return @{ Passed = $false; Message = "Test config file not found" }
        }
    }
    
    # Test ValidationEngine functionality
    Invoke-Test -TestName "ValidationEngine Parameter Validation" -Category "Unit" -TestScript {
        $params = @{
            TestParam = "TestValue"
            InvalidParam = $null
        }
        
        $schema = @{
            TestParam = @{ Type = 'string'; Required = $true }
            InvalidParam = @{ Type = 'string'; Required = $true }
        }
        
        $result = Test-Parameters -Parameters $params -Schema $schema
        $passed = (-not $result.IsValid) -and $result.Errors.Count -gt 0
        
        return @{
            Passed = $passed
            Message = if ($passed) { "Parameter validation working correctly" } else { "Parameter validation failed" }
            Details = @{ Errors = $result.Errors }
        }
    }
    
    # Test ErrorHandler functionality
    Invoke-Test -TestName "ErrorHandler Try-CatchBlock" -Category "Unit" -TestScript {
        $scriptExecuted = $false
        $errorCaught = $false
        
        $result = Try-CatchBlock -ScriptBlock {
            $script:scriptExecuted = $true
            throw "Test exception"
        } -Context "TestContext" -ContinueOnError -FinallyBlock {
            # Finally block should execute
        }
        
        $passed = $scriptExecuted -and ($null -eq $result)
        
        return @{
            Passed = $passed
            Message = if ($passed) { "Try-CatchBlock working correctly" } else { "Try-CatchBlock failed" }
        }
    }
    
    Write-TestLog "Unit tests completed" "INFO"
}

function Test-MockApiTests {
    Write-TestLog "Running mock API tests..." "INFO"
    
    # Test Mock vCenter API
    Invoke-Test -TestName "Mock vCenter Get-VMHost" -Category "Mock" -TestScript {
        # This would load and test mock vCenter functions
        $mockScript = "$PSScriptRoot\MockAPIs\MockVIServer.ps1"
        
        if (Test-Path $mockScript) {
            . $mockScript
            
            $hosts = Mock-GetVMHost -Name "test-host"
            $passed = ($null -ne $hosts -and $hosts.Count -gt 0)
            
            return @{
                Passed = $passed
                Message = if ($passed) { "Mock vCenter API working" } else { "Mock vCenter API failed" }
                Details = @{ HostCount = if ($hosts) { $hosts.Count } else { 0 } }
            }
        } else {
            return @{ Passed = $false; Message = "Mock vCenter script not found" }
        }
    }
    
    # Test Mock OneView API
    Invoke-Test -TestName "Mock OneView Get-HPOVServerHardware" -Category "Mock" -TestScript {
        $mockScript = "$PSScriptRoot\MockAPIs\MockOneView.ps1"
        
        if (Test-Path $mockScript) {
            . $mockScript
            
            $servers = Mock-GetHPOVServerHardware
            $passed = ($null -ne $servers -and $servers.Count -gt 0)
            
            return @{
                Passed = $passed
                Message = if ($passed) { "Mock OneView API working" } else { "Mock OneView API failed" }
                Details = @{ ServerCount = if ($servers) { $servers.Count } else { 0 } }
            }
        } else {
            return @{ Passed = $false; Message = "Mock OneView script not found" }
        }
    }
    
    Write-TestLog "Mock API tests completed" "INFO"
}

function Test-IntegrationTests {
    Write-TestLog "Running integration tests..." "INFO"
    
    # Test Configuration Integration
    Invoke-Test -TestName "Configuration Integration" -Category "Integration" -TestScript {
        $configFile = "config/settings.template.json"
        
        try {
            if (Test-Path $configFile) {
                # Load configuration
                $config = Get-Configuration -ConfigFile $configFile -SkipValidation
                
                # Test configuration merging
                $override = @{ system = @{ environment = "test" } }
                $merged = Merge-Configurations -BaseConfig $config -OverrideConfig $override
                
                $passed = ($merged.system.environment -eq "test")
                
                return @{
                    Passed = $passed
                    Message = if ($passed) { "Configuration integration working" } else { "Configuration integration failed" }
                    Details = @{ OriginalEnv = $config.system.environment; MergedEnv = $merged.system.environment }
                }
            } else {
                return @{ Passed = $false; Message = "Configuration file not found" }
            }
        } catch {
            return @{ Passed = $false; Message = "Configuration integration error: $($_.Exception.Message)" }
        }
    }
    
    # Test Logging Integration
    Invoke-Test -TestName "Logging Integration" -Category "Integration" -TestScript {
        $testLogFile = "temp/integration_test.log"
        
        try {
            # Ensure log directory exists
            $logDir = Split-Path $testLogFile -Parent
            if (-not (Test-Path $logDir)) {
                New-Item -Path $logDir -ItemType Directory -Force | Out-Null
            }
            
            # Test logging
            Write-EnhancedLog "Integration test message" "INFO" "IntegrationTest" -LogFile $testLogFile
            
            # Verify log entry
            if (Test-Path $testLogFile) {
                $logContent = Get-Content $testLogFile -Raw
                $passed = $logContent -contains "Integration test message"
                
                # Cleanup
                Remove-Item $testLogFile -Force
                
                return @{
                    Passed = $passed
                    Message = if ($passed) { "Logging integration working" } else { "Logging integration failed" }
                }
            } else {
                return @{ Passed = $false; Message = "Log file not created" }
            }
        } catch {
            return @{ Passed = $false; Message = "Logging integration error: $($_.Exception.Message)" }
        }
    }
    
    Write-TestLog "Integration tests completed" "INFO"
}

function Generate-TestReport {
    try {
        Write-TestLog "Generating test report..." "INFO"
        
        $endTime = Get-Date
        $totalDuration = ($endTime - $script:StartTime).TotalMinutes
        
        $passedTests = $script:TestResults | Where-Object { $_.Passed }
        $failedTests = $script:TestResults | Where-Object { -not $_.Passed }
        
        $report = [PSCustomObject]@{
            TestRunStartTime = $script:StartTime
            TestRunEndTime = $endTime
            TotalDurationMinutes = [math]::Round($totalDuration, 2)
            TestType = $TestType
            Simulation = $Simulation
            TotalTests = $script:TestResults.Count
            PassedTests = $passedTests.Count
            FailedTests = $failedTests.Count
            SuccessRate = if ($script:TestResults.Count -gt 0) { [math]::Round(($passedTests.Count / $script:TestResults.Count) * 100, 2) } else { 0 }
            OverallSuccess = ($failedTests.Count -eq 0)
            TestResults = $script:TestResults
            Categories = ($script:TestResults | Group-Object -Property Category | ForEach-Object { 
                @{
                    Category = $_.Name
                    Total = $_.Count
                    Passed = ($_.Group | Where-Object { $_.Passed }).Count
                    Failed = ($_.Group | Where-Object { -not $_.Passed }).Count
                }
            })
        }
        
        # Ensure reports directory exists
        if (-not (Test-Path "reports")) {
            New-Item -Path "reports" -ItemType Directory -Force | Out-Null
        }
        
        # Write report to file
        $reportJson = $report | ConvertTo-Json -Depth 10
        $reportJson | Out-File -FilePath $ReportFile -Encoding UTF8
        
        Write-TestLog "Test report saved to: $ReportFile" "SUCCESS"
        
        return $report
        
    } catch {
        Write-TestLog "Failed to generate test report: $($_.Exception.Message)" "ERROR"
        throw
    }
}

function Display-TestSummary {
    try {
        Write-TestLog "=== TEST SUMMARY ===" "SUCCESS"
        
        $endTime = Get-Date
        $duration = ($endTime - $script:StartTime).TotalMinutes
        
        Write-TestLog "Test execution time: $($duration.ToString('0.00')) minutes" "INFO"
        Write-TestLog "Test type: $TestType" "INFO"
        Write-TestLog "Total tests: $($script:TestResults.Count)" "INFO"
        
        $passedTests = $script:TestResults | Where-Object { $_.Passed }
        $failedTests = $script:TestResults | Where-Object { -not $_.Passed }
        
        Write-TestLog "Passed tests: $($passedTests.Count)" "SUCCESS"
        Write-TestLog "Failed tests: $($failedTests.Count)" if($failedTests.Count -gt 0) { "ERROR" } else { "SUCCESS" }
        
        if ($script:TestResults.Count -gt 0) {
            $successRate = [math]::Round(($passedTests.Count / $script:TestResults.Count) * 100, 2)
            Write-TestLog "Success rate: $successRate%" "INFO"
        }
        
        # Show failed tests if any
        if ($failedTests.Count -gt 0) {
            Write-TestLog "=== FAILED TESTS ===" "ERROR"
            foreach ($test in $failedTests) {
                Write-TestLog "FAILED: $($test.TestName) - $($test.Message)" "ERROR"
            }
        }
        
        $overallSuccess = ($failedTests.Count -eq 0)
        if ($overallSuccess) {
            Write-TestLog "=== ALL TESTS PASSED ===" "SUCCESS"
        } else {
            Write-TestLog "=== TESTS FAILED ===" "ERROR"
        }
        
        return $overallSuccess
        
    } catch {
        Write-TestLog "Failed to display test summary: $($_.Exception.Message)" "ERROR"
        return $false
    }
}

# Main execution
try {
    Write-TestLog "Starting test runner..." "INFO"
    Write-TestLog "Test type: $TestType" "INFO"
    Write-TestLog "Simulation: $Simulation" "INFO"
    Write-TestLog "Report file: $ReportFile" "INFO"
    
    # Execute requested tests
    switch ($TestType) {
        'Unit' { Test-UnitTests }
        'Mock' { Test-MockApiTests }
        'Integration' { Test-IntegrationTests }
        'All' {
            Test-UnitTests
            Test-MockApiTests
            Test-IntegrationTests
        }
        default {
            throw "Unknown test type: $TestType"
        }
    }
    
    # Generate report and display summary
    $report = Generate-TestReport
    $overallSuccess = Display-TestSummary
    
    return $report
    
} catch {
    Write-TestLog "TEST RUNNER FAILED: $($_.Exception.Message)" "ERROR"
    Write-TestLog "Stack trace: $($_.ScriptStackTrace)" "DEBUG"
    exit 1
    
} finally {
    # Cleanup
    try {
        Write-TestLog "Performing test cleanup..." "INFO"
        
        # Clean up temporary files
        $tempFiles = Get-ChildItem "temp" -ErrorAction SilentlyContinue
        foreach ($file in $tempFiles) {
            try {
                Remove-Item $file.FullName -Recurse -Force
            } catch {
                Write-TestLog "Failed to cleanup temp file: $($file.Name)" "WARN"
            }
        }
        
        Write-TestLog "Test cleanup completed" "SUCCESS"
        
    } catch {
        Write-TestLog "Cleanup failed: $($_.Exception.Message)" "ERROR"
    }
    
    Write-TestLog "=== TEST RUNNER FINISHED ===" "SUCCESS"
}
