<#
.SYNOPSIS
    Master workflow orchestrator for vSphere OneView automation suite.
.DESCRIPTION
    Comprehensive automation suite for HPE Synergy and vSphere infrastructure patching.
.PARAMETER Phase
    Specific phase to execute: Discovery, Staging, Execution, PostCheck, or All
.PARAMETER Simulation
    Run in simulation mode (default for safety)
.PARAMETER WhatIf
    Show what would happen without executing
.PARAMETER ConfigFile
    Path to configuration file
.PARAMETER LogFile
    Path to log file
.PARAMETER Environment
    Environment configuration to use
.EXAMPLE
    .\MasterWorkflow.ps1 -Phase Discovery -Simulation
.EXAMPLE
    .\MasterWorkflow.ps1 -Phase All -LogFile "custom.log"
.EXAMPLE
    .\MasterWorkflow.ps1 -Phase Execution -Environment production -Simulation:$false
.NOTES
    File Name      : MasterWorkflow.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+, VMware PowerCLI 12+, HPE OneView PowerShell Library
    Version        : 1.0.0
    Last Updated   : 2026-02-01
.LINK
    https://github.com/yourrepo/vsphere-oneview-automation
.OUTPUTS
    PSCustomObject with workflow results and statistics
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [ValidateSet('Discovery', 'Staging', 'Execution', 'PostCheck', 'All')]
    [string]$Phase = 'All',
    
    [Parameter(Mandatory=$false)]
    [switch]$Simulation = $true,
    
    [Parameter(Mandatory=$false)]
    [switch]$WhatIf,
    
    [Parameter(Mandatory=$false)]
    [string]$ConfigFile = "config/settings.json",
    
    [Parameter(Mandatory=$false)]
    [string]$LogFile = "logs/master/MasterWorkflow_$(Get-Date -Format 'yyyyMMdd_HHmm').log",
    
    [Parameter(Mandatory=$false)]
    [string]$Environment = $null
)

# Error handling
$ErrorActionPreference = "Stop"
$ProgressPreference = "Continue"

# Import utility functions
. "$PSScriptRoot\05_Utility\Logger.ps1"
. "$PSScriptRoot\05_Utility\ConfigManager.ps1"
. "$PSScriptRoot\05_Utility\CredentialManager.ps1"
. "$PSScriptRoot\05_Utility\ValidationEngine.ps1"
. "$PSScriptRoot\05_Utility\ErrorHandler.ps1"

# Initialize
$script:StartTime = Get-Date
$script:Component = "MasterWorkflow"
$global:LogFile = $LogFile
$script:Results = @()

function Initialize-Workflow {
    try {
        Write-EnhancedLog "=== VSPHERE ONEVIEW AUTOMATION SUITE ===" "SUCCESS" $script:Component
        Write-EnhancedLog "Master Workflow Orchestrator v1.0.0" "INFO" $script:Component
        Write-EnhancedLog "Phase: $Phase" "INFO" $script:Component
        Write-EnhancedLog "Simulation: $Simulation" "INFO" $script:Component
        Write-EnhancedLog "WhatIf: $WhatIf" "INFO" $script:Component
        Write-EnhancedLog "Environment: $Environment" "INFO" $script:Component
        Write-EnhancedLog "Config File: $ConfigFile" "INFO" $script:Component
        Write-EnhancedLog "Log File: $LogFile" "INFO" $script:Component
        Write-EnhancedLog "Started: $script:StartTime" "INFO" $script:Component
        
        # Create log header
        New-LogHeader -LogFile $LogFile -SessionInfo @{
            Phase = $Phase
            Simulation = $Simulation
            WhatIf = $WhatIf
            Environment = $Environment
            StartTime = $script:StartTime
        }
        
    } catch {
        Write-EnhancedLog "Failed to initialize workflow: $($_.Exception.Message)" "ERROR" $script:Component
        throw
    }
}

function Load-Configuration {
    try {
        Write-EnhancedLog "Loading configuration..." "INFO" $script:Component
        
        $configParams = @{
            ConfigFile = $ConfigFile
            SkipValidation = $false
        }
        
        if ($Environment) {
            $configParams.Environment = $Environment
        }
        
        $global:Config = Get-Configuration @configParams
        
        # Override simulation mode if specified
        if ($PSBoundParameters.ContainsKey('Simulation')) {
            $global:Config.system.simulationMode = $Simulation
        }
        
        Write-EnhancedLog "Configuration loaded successfully" "SUCCESS" $script:Component
        Write-EnhancedLog "Environment: $($global:Config.system.environment)" "INFO" $script:Component
        Write-EnhancedLog "Simulation mode: $($global:Config.system.simulationMode)" "INFO" $script:Component
        
        return $global:Config
        
    } catch {
        Write-EnhancedLog "Failed to load configuration: $($_.Exception.Message)" "ERROR" $script:Component
        throw
    }
}

function Validate-Prerequisites {
    try {
        Write-EnhancedLog "Validating prerequisites..." "INFO" $script:Component
        
        $prereqResult = Test-ScriptPrerequisites -Config $global:Config
        
        if (-not $prereqResult.IsValid) {
            Write-EnhancedLog "Prerequisites validation failed" "ERROR" $script:Component
            foreach ($error in $prereqResult.Errors) {
                Write-EnhancedLog "PREREQ ERROR: $error" "ERROR" $script:Component
            }
            throw "Prerequisites validation failed"
        }
        
        foreach ($warning in $prereqResult.Warnings) {
            Write-EnhancedLog "PREREQ WARNING: $warning" "WARN" $script:Component
        }
        
        Write-EnhancedLog "Prerequisites validation passed" "SUCCESS" $script:Component
        
    } catch {
        Write-EnhancedLog "Prerequisites validation error: $($_.Exception.Message)" "ERROR" $script:Component
        throw
    }
}

function Invoke-DiscoveryPhase {
    return Try-CatchBlock -ScriptBlock {
        Write-EnhancedLog "Starting Discovery Phase" "INFO" $script:Component
        
        $discoveryScript = Join-Path $PSScriptRoot "01_Discovery\RunDiscovery.ps1"
        if (-not (Test-Path $discoveryScript)) {
            throw "Discovery script not found: $discoveryScript"
        }
        
        $params = @{
            ConfigFile = $ConfigFile
            LogFile = "logs/discovery/Discovery_$(Get-Date -Format 'yyyyMMdd_HHmm').log"
            Simulation = $Simulation
            WhatIf = $WhatIf
        }
        
        $result = & $discoveryScript @params
        
        $script:Results += [PSCustomObject]@{
            Phase = "Discovery"
            StartTime = Get-Date
            EndTime = Get-Date
            Success = $true
            Result = $result
            Message = "Discovery phase completed successfully"
        }
        
        Write-EnhancedLog "Discovery phase completed" "SUCCESS" $script:Component
        
    } -Context "Discovery Phase" -RecoveryActions @(
        (New-RecoveryAction -Name "Retry discovery" -Action { param($ErrorInfo) return @{ Success = $true } })
    )
}

function Invoke-StagingPhase {
    return Try-CatchBlock -ScriptBlock {
        Write-EnhancedLog "Starting Staging Phase" "INFO" $script:Component
        
        $stagingScript = Join-Path $PSScriptRoot "02_Staging\RunStaging.ps1"
        if (-not (Test-Path $stagingScript)) {
            throw "Staging script not found: $stagingScript"
        }
        
        $params = @{
            ConfigFile = $ConfigFile
            LogFile = "logs/staging/Staging_$(Get-Date -Format 'yyyyMMdd_HHmm').log"
            Simulation = $Simulation
            WhatIf = $WhatIf
        }
        
        $result = & $stagingScript @params
        
        $script:Results += [PSCustomObject]@{
            Phase = "Staging"
            StartTime = Get-Date
            EndTime = Get-Date
            Success = $true
            Result = $result
            Message = "Staging phase completed successfully"
        }
        
        Write-EnhancedLog "Staging phase completed" "SUCCESS" $script:Component
        
    } -Context "Staging Phase" -RecoveryActions @(
        (New-RecoveryAction -Name "Retry staging" -Action { param($ErrorInfo) return @{ Success = $true } })
    )
}

function Invoke-ExecutionPhase {
    return Try-CatchBlock -ScriptBlock {
        Write-EnhancedLog "Starting Execution Phase" "INFO" $script:Component
        
        $executionScript = Join-Path $PSScriptRoot "03_Execution\RunExecution.ps1"
        if (-not (Test-Path $executionScript)) {
            throw "Execution script not found: $executionScript"
        }
        
        $params = @{
            ConfigFile = $ConfigFile
            LogFile = "logs/execution/Execution_$(Get-Date -Format 'yyyyMMdd_HHmm').log"
            Simulation = $Simulation
            WhatIf = $WhatIf
        }
        
        $result = & $executionScript @params
        
        $script:Results += [PSCustomObject]@{
            Phase = "Execution"
            StartTime = Get-Date
            EndTime = Get-Date
            Success = $true
            Result = $result
            Message = "Execution phase completed successfully"
        }
        
        Write-EnhancedLog "Execution phase completed" "SUCCESS" $script:Component
        
    } -Context "Execution Phase" -RecoveryActions @(
        (New-RecoveryAction -Name "Retry execution" -Action { param($ErrorInfo) return @{ Success = $true } })
    )
}

function Invoke-PostCheckPhase {
    return Try-CatchBlock -ScriptBlock {
        Write-EnhancedLog "Starting PostCheck Phase" "INFO" $script:Component
        
        $postCheckScript = Join-Path $PSScriptRoot "04_PostCheck\RunPostCheck.ps1"
        if (-not (Test-Path $postCheckScript)) {
            throw "PostCheck script not found: $postCheckScript"
        }
        
        $params = @{
            ConfigFile = $ConfigFile
            LogFile = "logs/postcheck/PostCheck_$(Get-Date -Format 'yyyyMMdd_HHmm').log"
            Simulation = $Simulation
            WhatIf = $WhatIf
        }
        
        $result = & $postCheckScript @params
        
        $script:Results += [PSCustomObject]@{
            Phase = "PostCheck"
            StartTime = Get-Date
            EndTime = Get-Date
            Success = $true
            Result = $result
            Message = "PostCheck phase completed successfully"
        }
        
        Write-EnhancedLog "PostCheck phase completed" "SUCCESS" $script:Component
        
    } -Context "PostCheck Phase" -RecoveryActions @(
        (New-RecoveryAction -Name "Retry postcheck" -Action { param($ErrorInfo) return @{ Success = $true } })
    )
}

function Generate-WorkflowReport {
    try {
        Write-EnhancedLog "Generating workflow report..." "INFO" $script:Component
        
        $endTime = Get-Date
        $totalDuration = ($endTime - $script:StartTime).TotalMinutes
        
        $successfulPhases = $script:Results | Where-Object { $_.Success }
        $failedPhases = $script:Results | Where-Object { -not $_.Success }
        
        $report = [PSCustomObject]@{
            WorkflowStartTime = $script:StartTime
            WorkflowEndTime = $endTime
            TotalDurationMinutes = [math]::Round($totalDuration, 2)
            RequestedPhase = $Phase
            Simulation = $Simulation
            WhatIf = $WhatIf
            Environment = $Environment
            TotalPhases = $script:Results.Count
            SuccessfulPhases = $successfulPhases.Count
            FailedPhases = $failedPhases.Count
            OverallSuccess = ($failedPhases.Count -eq 0)
            PhaseResults = $script:Results
            SystemInfo = Get-SystemInfo
            EnvironmentInfo = Get-EnvironmentInfo
        }
        
        # Write report to file
        $reportFile = "reports/WorkflowReport_$(Get-Date -Format 'yyyyMMdd_HHmm').json"
        
        # Ensure reports directory exists
        if (-not (Test-Path "reports")) {
            New-Item -Path "reports" -ItemType Directory -Force | Out-Null
        }
        
        $report | ConvertTo-Json -Depth 10 | Out-File -FilePath $reportFile -Encoding UTF8
        
        Write-EnhancedLog "Workflow report saved to: $reportFile" "SUCCESS" $script:Component
        
        return $report
        
    } catch {
        Write-EnhancedLog "Failed to generate workflow report: $($_.Exception.Message)" "ERROR" $script:Component
        throw
    }
}

function Display-Summary {
    try {
        Write-EnhancedLog "=== WORKFLOW SUMMARY ===" "SUCCESS" $script:Component
        
        $endTime = Get-Date
        $duration = ($endTime - $script:StartTime).TotalMinutes
        
        Write-EnhancedLog "Total execution time: $($duration.ToString('0.00')) minutes" "INFO" $script:Component
        Write-EnhancedLog "Phase executed: $Phase" "INFO" $script:Component
        Write-EnhancedLog "Simulation mode: $Simulation" "INFO" $script:Component
        Write-EnhancedLog "Phases completed: $($script:Results.Count)" "INFO" $script:Component
        
        foreach ($result in $script:Results) {
            $status = if ($result.Success) { "SUCCESS" } else { "FAILED" }
            Write-EnhancedLog "Phase $($result.Phase): $status - $($result.Message)" "INFO" $script:Component
        }
        
        if (($script:Results | Where-Object { -not $_.Success }).Count -eq 0) {
            Write-EnhancedLog "=== WORKFLOW COMPLETED SUCCESSFULLY ===" "SUCCESS" $script:Component
        } else {
            Write-EnhancedLog "=== WORKFLOW COMPLETED WITH ERRORS ===" "ERROR" $script:Component
        }
        
    } catch {
        Write-EnhancedLog "Failed to display summary: $($_.Exception.Message)" "ERROR" $script:Component
    }
}

# Main execution
try {
    Initialize-Workflow
    
    # Load and validate configuration
    Load-Configuration
    Validate-Prerequisites
    
    # Execute requested phases
    switch ($Phase) {
        'Discovery' { 
            Invoke-DiscoveryPhase 
        }
        'Staging' { 
            Invoke-StagingPhase 
        }
        'Execution' { 
            Invoke-ExecutionPhase 
        }
        'PostCheck' { 
            Invoke-PostCheckPhase 
        }
        'All' { 
            Write-EnhancedLog "Executing all phases sequentially" "INFO" $script:Component
            Invoke-DiscoveryPhase
            Invoke-StagingPhase
            Invoke-ExecutionPhase
            Invoke-PostCheckPhase
        }
        default {
            throw "Unknown phase: $Phase"
        }
    }
    
    # Generate report and display summary
    $report = Generate-WorkflowReport
    Display-Summary
    
    return $report
    
} catch {
    Write-EnhancedLog "WORKFLOW FAILED: $($_.Exception.Message)" "ERROR" $script:Component
    Write-EnhancedLog "Stack trace: $($_.ScriptStackTrace)" "DEBUG" $script:Component
    
    try {
        Write-FatalErrorReport -ErrorInfo @{
            Timestamp = Get-Date
            Context = "MasterWorkflow"
            Exception = $_.Exception
            ErrorMessage = $_.Exception.Message
            Phase = $Phase
            Simulation = $Simulation
            WhatIf = $WhatIf
        }
    } catch {
        Write-EnhancedLog "Failed to write fatal error report" "ERROR" $script:Component
    }
    
    exit 1
    
} finally {
    # Cleanup
    try {
        Write-EnhancedLog "Performing workflow cleanup..." "INFO" $script:Component
        
        # Disconnect all connections safely
        Disconnect-AllSafely
        
        # Clear error history (keep recent entries)
        Clear-ErrorHistory -KeepLast 50
        
        # Generate final statistics
        $errorStats = Get-ErrorStatistics
        if ($errorStats.TotalErrors -gt 0) {
            Write-EnhancedLog "Error Statistics: $($errorStats.TotalErrors) errors, Recovery success rate: $($errorStats.RecoverySuccessRate)%" "INFO" $script:Component
        }
        
        Write-EnhancedLog "Workflow cleanup completed" "SUCCESS" $script:Component
        
    } catch {
        Write-EnhancedLog "Cleanup failed: $($_.Exception.Message)" "ERROR" $script:Component
    }
    
    Write-EnhancedLog "=== WORKFLOW FINISHED ===" "SUCCESS" $script:Component
}
