<#
.SYNOPSIS
    Configuration management framework for vSphere OneView automation suite.
.DESCRIPTION
    Handles loading, validation, and management of JSON configuration files with schema validation.
.PARAMETER ConfigFile
    Path to configuration JSON file
.PARAMETER SchemaFile
    Path to JSON schema file for validation
.PARAMETER Environment
    Environment name to load specific configuration
.EXAMPLE
    Get-Configuration -ConfigFile "config/settings.json"
.EXAMPLE
    Get-Configuration -ConfigFile "config/settings.json" -Environment "production"
.NOTES
    File Name      : ConfigManager.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

function Get-Configuration {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$ConfigFile,
        
        [Parameter(Mandatory=$false)]
        [string]$SchemaFile,
        
        [Parameter(Mandatory=$false)]
        [string]$Environment,
        
        [Parameter(Mandatory=$false)]
        [switch]$SkipValidation
    )
    
    try {
        Write-EnhancedLog "Loading configuration from: $ConfigFile" "INFO" "ConfigManager"
        
        # Check if config file exists
        if (-not (Test-Path $ConfigFile)) {
            throw "Configuration file not found: $ConfigFile"
        }
        
        # Load base configuration
        $configJson = Get-Content $ConfigFile -Raw
        $config = $configJson | ConvertFrom-Json
        
        # Add metadata
        $config | Add-Member -NotePropertyName "configFile" -NotePropertyValue $ConfigFile
        $config | Add-Member -NotePropertyName "configDirectory" -NotePropertyValue (Split-Path $ConfigFile -Parent)
        
        # Load environment-specific configuration if specified
        if ($Environment) {
            $envConfigFile = Join-Path (Split-Path $ConfigFile -Parent) "environments\$Environment.json"
            if (Test-Path $envConfigFile) {
                Write-EnhancedLog "Loading environment configuration from: $envConfigFile" "INFO" "ConfigManager"
                $envConfigJson = Get-Content $envConfigFile -Raw
                $envConfig = $envConfigJson | ConvertFrom-Json
                
                # Merge configurations (environment overrides base)
                $config = Merge-Configurations -BaseConfig $config -OverrideConfig $envConfig
            } else {
                Write-EnhancedLog "Environment config file not found: $envConfigFile" "WARN" "ConfigManager"
            }
        }
        
        # Validate configuration if not skipped
        if (-not $SkipValidation) {
            if ($SchemaFile) {
                $validationResult = Test-ConfigurationSchema -Config $config -SchemaFile $SchemaFile
                if (-not $validationResult.IsValid) {
                    throw "Configuration schema validation failed: $($validationResult.Errors -join ', ')"
                }
                Write-EnhancedLog "Configuration schema validation passed" "SUCCESS" "ConfigManager"
            } else {
                # Default schema validation
                $validationResult = Test-ConfigurationValidity -Config $config
                if (-not $validationResult.IsValid) {
                    throw "Configuration validation failed: $($validationResult.Errors -join ', ')"
                }
                Write-EnhancedLog "Configuration validation passed" "SUCCESS" "ConfigManager"
            }
        }
        
        Write-EnhancedLog "Configuration loaded successfully for environment: $($config.system.environment)" "SUCCESS" "ConfigManager"
        return $config
        
    } catch {
        Write-EnhancedLog "Failed to load configuration: $($_.Exception.Message)" "ERROR" "ConfigManager"
        throw
    }
}

function Test-ConfigurationSchema {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$true)]
        [string]$SchemaFile
    )
    
    try {
        if (-not (Test-Path $SchemaFile)) {
            throw "Schema file not found: $SchemaFile"
        }
        
        # Load schema
        $schemaJson = Get-Content $SchemaFile -Raw
        $schema = $schemaJson | ConvertFrom-Json
        
        # Basic schema validation (simplified implementation)
        $errors = @()
        
        # Check required top-level properties
        $requiredProperties = @("system", "vCenter", "oneView")
        foreach ($prop in $requiredProperties) {
            if (-not ($Config.PSObject.Properties.Name -contains $prop)) {
                $errors += "Missing required property: $prop"
            }
        }
        
        # Check system properties
        if ($Config.system) {
            $systemRequired = @("version", "environment")
            foreach ($prop in $systemRequired) {
                if (-not ($Config.system.PSObject.Properties.Name -contains $prop)) {
                    $errors += "Missing required system property: $prop"
                }
            }
        }
        
        # Check vCenter properties
        if ($Config.vCenter) {
            $vcenterRequired = @("server", "credentialTarget")
            foreach ($prop in $vcenterRequired) {
                if (-not ($Config.vCenter.PSObject.Properties.Name -contains $prop)) {
                    $errors += "Missing required vCenter property: $prop"
                }
            }
        }
        
        # Check oneView properties
        if ($Config.oneView) {
            $oneviewRequired = @("appliance", "credentialTarget")
            foreach ($prop in $oneviewRequired) {
                if (-not ($Config.oneView.PSObject.Properties.Name -contains $prop)) {
                    $errors += "Missing required OneView property: $prop"
                }
            }
        }
        
        return [PSCustomObject]@{
            IsValid = ($errors.Count -eq 0)
            Errors = $errors
        }
        
    } catch {
        Write-EnhancedLog "Schema validation error: $($_.Exception.Message)" "ERROR" "ConfigManager"
        return [PSCustomObject]@{
            IsValid = $false
            Errors = @("Schema validation failed: $($_.Exception.Message)")
        }
    }
}

function Test-ConfigurationValidity {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config
    )
    
    try {
        $errors = @()
        
        # System section validation
        if ($Config.system) {
            if ($Config.system.environment -notin @("development", "staging", "production", "disaster-recovery")) {
                $errors += "Invalid environment: $($Config.system.environment)"
            }
            
            if ($Config.system.timeoutMinutes -and $Config.system.timeoutMinutes -lt 1) {
                $errors += "Timeout minutes must be greater than 0"
            }
        }
        
        # vCenter section validation
        if ($Config.vCenter) {
            if (-not $Config.vCenter.server) {
                $errors += "vCenter server name is required"
            }
            
            if ($Config.vCenter.port -and ($Config.vCenter.port -lt 1 -or $Config.vCenter.port -gt 65535)) {
                $errors += "vCenter port must be between 1 and 65535"
            }
        }
        
        # OneView section validation
        if ($Config.oneView) {
            if (-not $Config.oneView.appliance) {
                $errors += "OneView appliance name is required"
            }
            
            if ($Config.oneView.timeoutSeconds -and $Config.oneView.timeoutSeconds -lt 1) {
                $errors += "OneView timeout seconds must be greater than 0"
            }
        }
        
        # Execution section validation
        if ($Config.execution) {
            if ($Config.execution.parallelHosts -and $Config.execution.parallelHosts -lt 1) {
                $errors += "Parallel hosts must be at least 1"
            }
            
            if ($Config.execution.maintenanceModeTimeout -and $Config.execution.maintenanceModeTimeout -lt 1) {
                $errors += "Maintenance mode timeout must be greater than 0"
            }
        }
        
        # Safety section validation
        if ($Config.safety) {
            if ($Config.safety.heartbeatFailureThreshold -and $Config.safety.heartbeatFailureThreshold -lt 1) {
                $errors += "Heartbeat failure threshold must be at least 1"
            }
            
            if ($Config.safety.rollbackTimeout -and $Config.safety.rollbackTimeout -lt 1) {
                $errors += "Rollback timeout must be greater than 0"
            }
        }
        
        return [PSCustomObject]@{
            IsValid = ($errors.Count -eq 0)
            Errors = $errors
        }
        
    } catch {
        Write-EnhancedLog "Configuration validation error: $($_.Exception.Message)" "ERROR" "ConfigManager"
        return [PSCustomObject]@{
            IsValid = $false
            Errors = @("Configuration validation failed: $($_.Exception.Message)")
        }
    }
}

function Merge-Configurations {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$BaseConfig,
        
        [Parameter(Mandatory=$true)]
        [object]$OverrideConfig
    )
    
    try {
        # Create a deep copy of base config
        $mergedConfig = $BaseConfig | ConvertTo-Json -Depth 100 | ConvertFrom-Json
        
        # Recursively merge configurations
        Merge-Object -Target $mergedConfig -Source $OverrideConfig
        
        Write-EnhancedLog "Configuration merge completed successfully" "SUCCESS" "ConfigManager"
        return $mergedConfig
        
    } catch {
        Write-EnhancedLog "Configuration merge failed: $($_.Exception.Message)" "ERROR" "ConfigManager"
        throw
    }
}

function Merge-Object {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Target,
        
        [Parameter(Mandatory=$true)]
        [object]$Source
    )
    
    foreach ($property in $Source.PSObject.Properties) {
        if ($property.Value -is [PSCustomObject] -and $Target.PSObject.Properties.Name -contains $property.Name) {
            # Recursively merge nested objects
            Merge-Object -Target $Target.$($property.Name) -Source $property.Value
        } else {
            # Override or add property
            $Target | Add-Member -NotePropertyName $property.Name -NotePropertyValue $property.Value -Force
        }
    }
}

function Export-Configuration {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$true)]
        [string]$OutputFile,
        
        [Parameter(Mandatory=$false)]
        [switch]$Pretty
    )
    
    try {
        Write-EnhancedLog "Exporting configuration to: $OutputFile" "INFO" "ConfigManager"
        
        # Ensure output directory exists
        $outputDir = Split-Path $OutputFile -Parent
        if (-not (Test-Path $outputDir)) {
            New-Item -Path $outputDir -ItemType Directory -Force | Out-Null
        }
        
        # Convert to JSON
        if ($Pretty) {
            $json = $Config | ConvertTo-Json -Depth 100
        } else {
            $json = $Config | ConvertTo-Json -Depth 100 -Compress
        }
        
        # Write to file
        $json | Out-File -FilePath $OutputFile -Encoding UTF8
        
        Write-EnhancedLog "Configuration exported successfully" "SUCCESS" "ConfigManager"
        
    } catch {
        Write-EnhancedLog "Failed to export configuration: $($_.Exception.Message)" "ERROR" "ConfigManager"
        throw
    }
}

function New-ConfigurationTemplate {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$OutputFile,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("settings", "credentials", "email")]
        [string]$TemplateType = "settings"
    )
    
    try {
        Write-EnhancedLog "Creating configuration template: $TemplateType" "INFO" "ConfigManager"
        
        $template = switch ($TemplateType) {
            "settings" {
                @{
                    system = @{
                        version = "1.0.0"
                        environment = "production"
                        debugMode = $false
                        simulationMode = $true
                        logLevel = "INFO"
                        timeoutMinutes = 90
                    }
                    vCenter = @{
                        server = "vcenter.domain.com"
                        port = 443
                        protocol = "https"
                        credentialTarget = "vcenter-admin"
                        clusterName = "Production_Cluster"
                        datacenterName = "Datacenter"
                        defaultDatastore = "datastore1"
                    }
                    oneView = @{
                        appliance = "synergy-composer.domain.com"
                        apiVersion = "1200"
                        credentialTarget = "oneview-admin"
                        defaultSPP = "Synergy Service Pack 2023.12"
                        timeoutSeconds = 1800
                    }
                    execution = @{
                        parallelHosts = 1
                        maintenanceModeTimeout = 30
                        vMotionTimeout = 60
                        firmwareUpdateTimeout = 90
                        rebootTimeout = 30
                        postRebootWait = 5
                    }
                    safety = @{
                        enableHeartbeat = $true
                        heartbeatFailureThreshold = 2
                        enableRollback = $true
                        rollbackTimeout = 20
                        requireNMinusOneCapacity = $true
                        maxConcurrentOperations = 1
                    }
                }
            }
            "credentials" {
                @{
                    vCenter = @{
                        username = "administrator@vsphere.local"
                        password = "ENCRYPTED_PASSWORD_PLACEHOLDER"
                    }
                    oneView = @{
                        username = "admin"
                        password = "ENCRYPTED_PASSWORD_PLACEHOLDER"
                    }
                    smtp = @{
                        username = "smtp-user"
                        password = "ENCRYPTED_PASSWORD_PLACEHOLDER"
                    }
                }
            }
            "email" {
                @{
                    enabled = $false
                    smtpServer = "smtp.domain.com"
                    smtpPort = 587
                    useSSL = $true
                    from = "automation@domain.com"
                    to = @("admin@domain.com")
                    credentialTarget = "smtp-auth"
                }
            }
        }
        
        Export-Configuration -Config $template -OutputFile $OutputFile -Pretty
        Write-EnhancedLog "Configuration template created: $OutputFile" "SUCCESS" "ConfigManager"
        
    } catch {
        Write-EnhancedLog "Failed to create configuration template: $($_.Exception.Message)" "ERROR" "ConfigManager"
        throw
    }
}

# Export functions if this file is imported as a module
Export-ModuleMember -Function Get-Configuration, Test-ConfigurationSchema, Test-ConfigurationValidity, Merge-Configurations, Merge-Object, Export-Configuration, New-ConfigurationTemplate
