<#
.SYNOPSIS
    Robust connection management framework for vSphere and OneView.
.DESCRIPTION
    Provides safe connection handling with health checks, retry logic, and proper cleanup.
.PARAMETER Server
    Server name or IP address
.PARAMETER Credential
    PSCredential object for authentication
.PARAMETER TimeoutSeconds
    Connection timeout in seconds
.PARAMETER TestConnection
    Perform health check after connection
.PARAMETER MaxRetries
    Maximum number of connection retries
.PARAMETER RetryDelaySeconds
    Delay between retries in seconds
.EXAMPLE
    Connect-vCenterSafely -Server "vcenter.domain.com" -Credential $cred -TestConnection
.EXAMPLE
    Connect-OneViewSafely -Appliance "oneview.domain.com" -Credential $cred
.NOTES
    File Name      : ConnectionManager.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+, VMware PowerCLI 12+, HPE OneView PowerShell Library
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

function Connect-vCenterSafely {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$Server,
        
        [Parameter(Mandatory=$true)]
        [PSCredential]$Credential,
        
        [Parameter(Mandatory=$false)]
        [int]$TimeoutSeconds = 30,
        
        [Parameter(Mandatory=$false)]
        [switch]$TestConnection,
        
        [Parameter(Mandatory=$false)]
        [int]$MaxRetries = 3,
        
        [Parameter(Mandatory=$false)]
        [int]$RetryDelaySeconds = 10
    )
    
    $attempt = 0
    $lastError = $null
    
    while ($attempt -lt $MaxRetries) {
        $attempt++
        
        try {
            Write-EnhancedLog "Connecting to vCenter: $Server (attempt $attempt/$MaxRetries)" "INFO" "vCenter"
            
            # Check server connectivity first
            if (-not (Test-NetConnection -ComputerName $Server -Port 443 -WarningAction SilentlyContinue).TcpTestSucceeded) {
                throw "Network connectivity test to $Server:443 failed"
            }
            
            # Connect to vCenter
            $connection = Connect-VIServer -Server $Server -Credential $Credential -TimeoutSec $TimeoutSeconds -ErrorAction Stop
            
            if (-not $connection) {
                throw "Connection returned null"
            }
            
            Write-EnhancedLog "Successfully connected to vCenter: $Server" "SUCCESS" "vCenter"
            
            # Perform health check if requested
            if ($TestConnection) {
                $healthResult = Test-vCenterConnection -Connection $connection
                if (-not $healthResult.Success) {
                    throw "Connection health check failed: $($healthResult.Message)"
                }
                Write-EnhancedLog "vCenter connection health check passed" "SUCCESS" "vCenter"
            }
            
            # Store connection for cleanup
            $script:vCenterConnections = @($script:vCenterConnections) + $connection
            
            return $connection
            
        } catch {
            $lastError = $_
            Write-EnhancedLog "vCenter connection attempt $attempt failed: $($_.Exception.Message)" "ERROR" "vCenter"
            
            if ($attempt -lt $MaxRetries) {
                Write-EnhancedLog "Retrying in $RetryDelaySeconds seconds..." "WARN" "vCenter"
                Start-Sleep -Seconds $RetryDelaySeconds
            }
        }
    }
    
    # All retries failed
    $finalError = "Failed to connect to vCenter after $MaxRetries attempts. Last error: $($lastError.Exception.Message)"
    Write-EnhancedLog $finalError "ERROR" "vCenter"
    throw $finalError
}

function Test-vCenterConnection {
    [CmdletBinding()]
    param($Connection)
    
    try {
        Write-EnhancedLog "Performing vCenter connection health check" "INFO" "vCenter"
        
        # Test basic operations
        $datacenter = Get-Datacenter -Server $Connection -ErrorAction Stop | Select-Object -First 1
        if (-not $datacenter) {
            throw "Unable to retrieve Datacenter objects"
        }
        
        # Test VM operations
        $testVM = Get-VM -Server $Connection -ErrorAction Stop | Select-Object -First 1
        Write-EnhancedLog "Datacenter: $($datacenter.Name), Sample VM: $($testVM.Name)" "DEBUG" "vCenter"
        
        # Test service instance
        $serviceInstance = Get-View ServiceInstance -Server $Connection -ErrorAction Stop
        if (-not $serviceInstance) {
            throw "Unable to access ServiceInstance"
        }
        
        # Check API version
        $apiVersion = $serviceInstance.Content.About.Version
        Write-EnhancedLog "vCenter API version: $apiVersion" "INFO" "vCenter"
        
        return [PSCustomObject]@{ 
            Success = $true 
            Message = "Connection healthy" 
            Datacenter = $datacenter.Name
            APIVersion = $apiVersion
        }
        
    } catch {
        $errorMsg = "vCenter health check failed: $($_.Exception.Message)"
        Write-EnhancedLog $errorMsg "ERROR" "vCenter"
        return [PSCustomObject]@{ 
            Success = $false 
            Message = $errorMsg 
        }
    }
}

function Connect-OneViewSafely {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$Appliance,
        
        [Parameter(Mandatory=$false)]
        [PSCredential]$Credential,
        
        [Parameter(Mandatory=$false)]
        [string]$Username,
        
        [Parameter(Mandatory=$false)]
        [string]$Password,
        
        [Parameter(Mandatory=$false)]
        [int]$TimeoutSeconds = 30,
        
        [Parameter(Mandatory=$false)]
        [switch]$TestConnection,
        
        [Parameter(Mandatory=$false)]
        [int]$MaxRetries = 3,
        
        [Parameter(Mandatory=$false)]
        [int]$RetryDelaySeconds = 10
    )
    
    # Handle credential parameters
    if (-not $Credential -and $Username -and $Password) {
        $securePassword = ConvertTo-SecureString -String $Password -AsPlainText -Force
        $Credential = New-Object System.Management.Automation.PSCredential($Username, $securePassword)
    }
    
    if (-not $Credential) {
        throw "Either Credential parameter or Username/Password parameters must be provided"
    }
    
    $attempt = 0
    $lastError = $null
    
    while ($attempt -lt $MaxRetries) {
        $attempt++
        
        try {
            Write-EnhancedLog "Connecting to OneView: $Appliance (attempt $attempt/$MaxRetries)" "INFO" "OneView"
            
            # Check server connectivity first
            if (-not (Test-NetConnection -ComputerName $Appliance -Port 443 -WarningAction SilentlyContinue).TcpTestSucceeded) {
                throw "Network connectivity test to $Appliance:443 failed"
            }
            
            # Connect to OneView
            $connection = Connect-HPOVResource -Appliance $Appliance -UserName $Credential.UserName -Password $Credential.GetNetworkCredential().Password -ErrorAction Stop
            
            if (-not $connection) {
                throw "Connection returned null"
            }
            
            Write-EnhancedLog "Successfully connected to OneView: $Appliance" "SUCCESS" "OneView"
            
            # Perform health check if requested
            if ($TestConnection) {
                $healthResult = Test-OneViewConnection -Connection $connection
                if (-not $healthResult.Success) {
                    throw "Connection health check failed: $($healthResult.Message)"
                }
                Write-EnhancedLog "OneView connection health check passed" "SUCCESS" "OneView"
            }
            
            # Store connection for cleanup
            $script:oneViewConnections = @($script:oneViewConnections) + $connection
            
            return $connection
            
        } catch {
            $lastError = $_
            Write-EnhancedLog "OneView connection attempt $attempt failed: $($_.Exception.Message)" "ERROR" "OneView"
            
            if ($attempt -lt $MaxRetries) {
                Write-EnhancedLog "Retrying in $RetryDelaySeconds seconds..." "WARN" "OneView"
                Start-Sleep -Seconds $RetryDelaySeconds
            }
        }
    }
    
    # All retries failed
    $finalError = "Failed to connect to OneView after $MaxRetries attempts. Last error: $($lastError.Exception.Message)"
    Write-EnhancedLog $finalError "ERROR" "OneView"
    throw $finalError
}

function Test-OneViewConnection {
    [CmdletBinding()]
    param($Connection)
    
    try {
        Write-EnhancedLog "Performing OneView connection health check" "INFO" "OneView"
        
        # Test basic operations
        $applianceInfo = Get-HPOVApplianceInfo -ErrorAction Stop
        if (-not $applianceInfo) {
            throw "Unable to retrieve appliance information"
        }
        
        # Test hardware access
        $testServer = Get-HPOVServerHardware -ErrorAction Stop | Select-Object -First 1
        Write-EnhancedLog "Appliance: $($applianceInfo.model), Sample server: $($testServer.Name)" "DEBUG" "OneView"
        
        # Test API version
        $apiVersion = $applianceInfo.apiVersion
        Write-EnhancedLog "OneView API version: $apiVersion" "INFO" "OneView"
        
        return [PSCustomObject]@{ 
            Success = $true 
            Message = "Connection healthy" 
            ApplianceModel = $applianceInfo.model
            APIVersion = $apiVersion
            ServerCount = (Get-HPOVServerHardware).Count
        }
        
    } catch {
        $errorMsg = "OneView health check failed: $($_.Exception.Message)"
        Write-EnhancedLog $errorMsg "ERROR" "OneView"
        return [PSCustomObject]@{ 
            Success = $false 
            Message = $errorMsg 
        }
    }
}

function Disconnect-AllSafely {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [switch]$Force = $false
    )
    
    try {
        Write-EnhancedLog "Disconnecting all connections..." "INFO" "ConnectionManager"
        
        # Disconnect vCenter connections
        if ($script:vCenterConnections) {
            foreach ($connection in $script:vCenterConnections) {
                if ($connection.IsConnected) {
                    try {
                        Write-EnhancedLog "Disconnecting from vCenter: $($connection.Name)" "INFO" "vCenter"
                        Disconnect-VIServer -Server $connection -Confirm:$false -ErrorAction SilentlyContinue
                    } catch {
                        Write-EnhancedLog "Error disconnecting from vCenter: $($_.Exception.Message)" "WARN" "vCenter"
                    }
                }
            }
            $script:vCenterConnections = @()
        }
        
        # Disconnect OneView connections
        if ($script:oneViewConnections) {
            foreach ($connection in $script:oneViewConnections) {
                try {
                    Write-EnhancedLog "Disconnecting from OneView" "INFO" "OneView"
                    Disconnect-HPOVResource -ErrorAction SilentlyContinue
                } catch {
                    Write-EnhancedLog "Error disconnecting from OneView: $($_.Exception.Message)" "WARN" "OneView"
                }
            }
            $script:oneViewConnections = @()
        }
        
        Write-EnhancedLog "All connections disconnected successfully" "SUCCESS" "ConnectionManager"
        
    } catch {
        Write-EnhancedLog "Error during disconnection: $($_.Exception.Message)" "ERROR" "ConnectionManager"
        if ($Force) {
            # Force disconnect by clearing connection variables
            $script:vCenterConnections = @()
            $script:oneViewConnections = @()
            Write-EnhancedLog "Forced disconnection completed" "WARN" "ConnectionManager"
        } else {
            throw
        }
    }
}

function Test-SystemConnectivity {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string[]]$Targets,
        
        [Parameter(Mandatory=$false)]
        [int]$Port = 443,
        
        [Parameter(Mandatory=$false)]
        [int]$TimeoutMs = 5000
    )
    
    $results = @()
    
    foreach ($target in $Targets) {
        try {
            Write-EnhancedLog "Testing connectivity to $target`:$Port" "INFO" "ConnectionManager"
            
            $testResult = Test-NetConnection -ComputerName $target -Port $Port -WarningAction SilentlyContinue
            
            $result = [PSCustomObject]@{
                Target = $target
                Port = $Port
                TcpTestSucceeded = $testResult.TcpTestSucceeded
                PingSucceeded = $testResult.PingSucceeded
                NameResolveSucceeded = $testResult.NameResolutionSucceeded
                InterfaceAlias = $testResult.InterfaceAlias
                SourceAddress = $testResult.SourceAddress
                PingReplyDetails = $testResult.PingReplyDetails
                Timestamp = Get-Date
            }
            
            if ($testResult.TcpTestSucceeded) {
                Write-EnhancedLog "Connectivity test to $target`:$Port: SUCCESS" "SUCCESS" "ConnectionManager"
            } else {
                Write-EnhancedLog "Connectivity test to $target`:$Port: FAILED" "ERROR" "ConnectionManager"
            }
            
            $results += $result
            
        } catch {
            Write-EnhancedLog "Error testing connectivity to $target: $($_.Exception.Message)" "ERROR" "ConnectionManager"
            $results += [PSCustomObject]@{
                Target = $target
                Port = $Port
                TcpTestSucceeded = $false
                Error = $_.Exception.Message
                Timestamp = Get-Date
            }
        }
    }
    
    return $results
}

# Initialize connection tracking
$script:vCenterConnections = @()
$script:oneViewConnections = @()

# Export functions if this file is imported as a module
Export-ModuleMember -Function Connect-vCenterSafely, Test-vCenterConnection, Connect-OneViewSafely, Test-OneViewConnection, Disconnect-AllSafely, Test-SystemConnectivity
