<#
.SYNOPSIS
    Secure credential management framework for vSphere OneView automation suite.
.DESCRIPTION
    Provides secure storage and retrieval of credentials using Windows Credential Manager, encrypted files, or environment variables.
.PARAMETER TargetName
    Name/identifier for the credential
.PARAMETER Credential
    PSCredential object to store
.PARAMETER CredentialStore
    Type of credential storage: Windows, File, Environment
.PARAMETER Description
    Description for the credential
.EXAMPLE
    New-SecureCredential -TargetName "vcenter-admin" -Credential $cred
.EXAMPLE
    Get-SecureCredential -TargetName "vcenter-admin"
.NOTES
    File Name      : CredentialManager.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

function Get-SecureCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("Windows", "File", "Environment")]
        [string]$CredentialStore = "Windows",
        
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials"
    )
    
    try {
        Write-EnhancedLog "Retrieving credential: $TargetName from $CredentialStore store" "INFO" "CredentialManager"
        
        $credential = switch ($CredentialStore) {
            "Windows" {
                Get-WindowsCredential -TargetName $TargetName
            }
            "File" {
                Get-FileCredential -TargetName $TargetName -StorePath $StorePath
            }
            "Environment" {
                Get-EnvironmentCredential -TargetName $TargetName
            }
        }
        
        if ($credential) {
            Write-EnhancedLog "Credential retrieved successfully: $TargetName" "SUCCESS" "CredentialManager"
        } else {
            throw "Credential not found: $TargetName"
        }
        
        return $credential
        
    } catch {
        Write-EnhancedLog "Failed to retrieve credential $TargetName: $($_.Exception.Message)" "ERROR" "CredentialManager"
        throw
    }
}

function New-SecureCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$true)]
        [PSCredential]$Credential,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("Windows", "File", "Environment")]
        [string]$CredentialStore = "Windows",
        
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials",
        
        [Parameter(Mandatory=$false)]
        [string]$Description = "vSphere OneView Automation Credential"
    )
    
    try {
        Write-EnhancedLog "Storing credential: $TargetName in $CredentialStore store" "INFO" "CredentialManager"
        
        switch ($CredentialStore) {
            "Windows" {
                Set-WindowsCredential -TargetName $TargetName -Credential $Credential -Description $Description
            }
            "File" {
                Set-FileCredential -TargetName $TargetName -Credential $Credential -StorePath $StorePath
            }
            "Environment" {
                Set-EnvironmentCredential -TargetName $TargetName -Credential $Credential
            }
        }
        
        Write-EnhancedLog "Credential stored successfully: $TargetName" "SUCCESS" "CredentialManager"
        
    } catch {
        Write-EnhancedLog "Failed to store credential $TargetName: $($_.Exception.Message)" "ERROR" "CredentialManager"
        throw
    }
}

function Remove-SecureCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("Windows", "File", "Environment")]
        [string]$CredentialStore = "Windows",
        
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials"
    )
    
    try {
        Write-EnhancedLog "Removing credential: $TargetName from $CredentialStore store" "INFO" "CredentialManager"
        
        switch ($CredentialStore) {
            "Windows" {
                Remove-WindowsCredential -TargetName $TargetName
            }
            "File" {
                Remove-FileCredential -TargetName $TargetName -StorePath $StorePath
            }
            "Environment" {
                Remove-EnvironmentCredential -TargetName $TargetName
            }
        }
        
        Write-EnhancedLog "Credential removed successfully: $TargetName" "SUCCESS" "CredentialManager"
        
    } catch {
        Write-EnhancedLog "Failed to remove credential $TargetName: $($_.Exception.Message)" "ERROR" "CredentialManager"
        throw
    }
}

function Get-WindowsCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName
    )
    
    try {
        # Try to get credential from Windows Credential Manager
        $credential = Get-StoredCredential -Target $TargetName -ErrorAction SilentlyContinue
        
        if ($credential) {
            return $credential
        } else {
            throw "Windows credential not found: $TargetName"
        }
        
    } catch {
        throw "Windows credential retrieval failed: $($_.Exception.Message)"
    }
}

function Set-WindowsCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$true)]
        [PSCredential]$Credential,
        
        [Parameter(Mandatory=$false)]
        [string]$Description
    )
    
    try {
        # Store credential in Windows Credential Manager
        $params = @{
            Target = $TargetName
            Credential = $Credential
            Persist = "LocalMachine"
        }
        
        if ($Description) {
            $params.Comment = $Description
        }
        
        New-StoredCredential @params -ErrorAction Stop
        
    } catch {
        throw "Windows credential storage failed: $($_.Exception.Message)"
    }
}

function Remove-WindowsCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName
    )
    
    try {
        # Remove credential from Windows Credential Manager
        Remove-StoredCredential -Target $TargetName -ErrorAction Stop
        
    } catch {
        throw "Windows credential removal failed: $($_.Exception.Message)"
    }
}

function Get-FileCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials"
    )
    
    try {
        $credentialPath = Join-Path $StorePath "$TargetName.cred"
        
        if (-not (Test-Path $credentialPath)) {
            throw "File credential not found: $credentialPath"
        }
        
        # Read encrypted password
        $secureString = Get-Content $credentialPath | ConvertTo-SecureString -ErrorAction Stop
        
        # Get username from separate file (for security)
        $usernamePath = Join-Path $StorePath "$TargetName.user"
        $username = if (Test-Path $usernamePath) { 
            Get-Content $usernamePath 
        } else { 
            # Fallback to target name
            $TargetName 
        }
        
        # Create credential object
        $credential = New-Object System.Management.Automation.PSCredential($username, $secureString)
        
        return $credential
        
    } catch {
        throw "File credential retrieval failed: $($_.Exception.Message)"
    }
}

function Set-FileCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$true)]
        [PSCredential]$Credential,
        
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials"
    )
    
    try {
        # Ensure store directory exists
        if (-not (Test-Path $StorePath)) {
            New-Item -Path $StorePath -ItemType Directory -Force | Out-Null
        }
        
        $credentialPath = Join-Path $StorePath "$TargetName.cred"
        $usernamePath = Join-Path $StorePath "$TargetName.user"
        
        # Store encrypted password
        $Credential.Password | ConvertFrom-SecureString | Out-File -FilePath $credentialPath -Encoding UTF8
        
        # Store username separately (for better security)
        $Credential.UserName | Out-File -FilePath $usernamePath -Encoding UTF8
        
    } catch {
        throw "File credential storage failed: $($_.Exception.Message)"
    }
}

function Remove-FileCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials"
    )
    
    try {
        $credentialPath = Join-Path $StorePath "$TargetName.cred"
        $usernamePath = Join-Path $StorePath "$TargetName.user"
        
        if (Test-Path $credentialPath) {
            Remove-Item $credentialPath -Force
        }
        
        if (Test-Path $usernamePath) {
            Remove-Item $usernamePath -Force
        }
        
    } catch {
        throw "File credential removal failed: $($_.Exception.Message)"
    }
}

function Get-EnvironmentCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName
    )
    
    try {
        $username = Get-Content "env:${TargetName}_USERNAME" -ErrorAction SilentlyContinue
        $password = Get-Content "env:${TargetName}_PASSWORD" -ErrorAction SilentlyContinue
        
        if (-not $username -or -not $password) {
            throw "Environment variables not found for: $TargetName"
        }
        
        $securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)
        
        return $credential
        
    } catch {
        throw "Environment credential retrieval failed: $($_.Exception.Message)"
    }
}

function Set-EnvironmentCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$true)]
        [PSCredential]$Credential
    )
    
    try {
        # Note: Environment variables are typically read-only in many environments
        # This function is primarily for documentation purposes
        Write-EnhancedLog "Environment variables are typically read-only. Please set ${TargetName}_USERNAME and ${TargetName}_PASSWORD manually." "WARN" "CredentialManager"
        
    } catch {
        throw "Environment credential storage not supported"
    }
}

function Remove-EnvironmentCredential {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName
    )
    
    try {
        # Remove environment variables (if supported)
        Remove-Item "env:${TargetName}_USERNAME" -ErrorAction SilentlyContinue
        Remove-Item "env:${TargetName}_PASSWORD" -ErrorAction SilentlyContinue
        
    } catch {
        Write-EnhancedLog "Environment credential removal may not be supported" "WARN" "CredentialManager"
    }
}

function Test-CredentialAvailability {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$TargetName,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("Windows", "File", "Environment")]
        [string]$CredentialStore = "Windows",
        
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials"
    )
    
    try {
        switch ($CredentialStore) {
            "Windows" {
                $credential = Get-StoredCredential -Target $TargetName -ErrorAction SilentlyContinue
                return $null -ne $credential
            }
            "File" {
                $credentialPath = Join-Path $StorePath "$TargetName.cred"
                return Test-Path $credentialPath
            }
            "Environment" {
                $username = Get-Content "env:${TargetName}_USERNAME" -ErrorAction SilentlyContinue
                $password = Get-Content "env:${TargetName}_PASSWORD" -ErrorAction SilentlyContinue
                return ($null -ne $username -and $null -ne $password)
            }
        }
        
        return $false
        
    } catch {
        Write-EnhancedLog "Error testing credential availability: $($_.Exception.Message)" "ERROR" "CredentialManager"
        return $false
    }
}

function Get-CredentialStoreInfo {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [string]$StorePath = "config/credentials"
    )
    
    try {
        $stores = @()
        
        # Check Windows Credential Manager
        try {
            $windowsCreds = Get-StoredCredential -ErrorAction SilentlyContinue
            $stores += [PSCustomObject]@{
                StoreType = "Windows"
                Available = $true
                CredentialCount = if ($windowsCreds) { 1 } else { 0 }
                Path = "Windows Credential Manager"
            }
        } catch {
            $stores += [PSCustomObject]@{
                StoreType = "Windows"
                Available = $false
                CredentialCount = 0
                Path = "Windows Credential Manager"
                Error = $_.Exception.Message
            }
        }
        
        # Check File store
        $fileStoreAvailable = Test-Path $StorePath
        $fileCredentials = if ($fileStoreAvailable) { 
            Get-ChildItem $StorePath -Filter "*.cred" | Measure-Object | Select-Object -ExpandProperty Count
        } else { 
            0 
        }
        
        $stores += [PSCustomObject]@{
            StoreType = "File"
            Available = $fileStoreAvailable
            CredentialCount = $fileCredentials
            Path = $StorePath
        }
        
        # Check Environment store
        $envVars = Get-ChildItem env:* | Where-Object { $_.Name -match "_USERNAME$|_PASSWORD$" }
        $stores += [PSCustomObject]@{
            StoreType = "Environment"
            Available = $true
            CredentialCount = [math]::Floor($envVars.Count / 2)
            Path = "Environment Variables"
        }
        
        return $stores
        
    } catch {
        Write-EnhancedLog "Error getting credential store info: $($_.Exception.Message)" "ERROR" "CredentialManager"
        return @()
    }
}

# Export functions if this file is imported as a module
Export-ModuleMember -Function Get-SecureCredential, New-SecureCredential, Remove-SecureCredential, Test-CredentialAvailability, Get-CredentialStoreInfo
