<#
.SYNOPSIS
    Error handling and recovery framework for vSphere OneView automation suite.
.DESCRIPTION
    Provides centralized error handling, logging, and recovery mechanisms.
.PARAMETER ErrorRecord
    PowerShell ErrorRecord object
.PARAMETER Context
    Context information for the error
.PARAMETER RecoveryActions
    Recovery actions to attempt
.PARAMETER FatalError
    Whether the error should terminate execution
.EXAMPLE
    Invoke-ErrorHandling -ErrorRecord $_ -Context "vCenter connection" -RecoveryActions $recoveryActions
.EXAMPLE
    Try-CatchBlock -ScriptBlock $scriptBlock -Context "Host processing" -RecoveryActions $recovery
.NOTES
    File Name      : ErrorHandler.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

function Invoke-ErrorHandling {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [System.Management.Automation.ErrorRecord]$ErrorRecord,
        
        [Parameter(Mandatory=$false)]
        [string]$Context = "Unknown",
        
        [Parameter(Mandatory=$false)]
        [scriptblock[]]$RecoveryActions = @(),
        
        [Parameter(Mandatory=$false)]
        [switch]$FatalError,
        
        [Parameter(Mandatory=$false)]
        [hashtable]$Metadata = @{}
    )
    
    try {
        # Create error object
        $errorInfo = [PSCustomObject]@{
            Timestamp = Get-Date
            Context = $Context
            ErrorRecord = $ErrorRecord
            Exception = $ErrorRecord.Exception
            ErrorMessage = $ErrorRecord.Exception.Message
            ErrorType = $ErrorRecord.Exception.GetType().Name
            StackTrace = $ErrorRecord.ScriptStackTrace
            Command = $ErrorRecord.InvocationInfo.Command
            Line = $ErrorRecord.InvocationInfo.ScriptLineNumber
            Position = $ErrorRecord.InvocationInfo.OffsetInLine
            Metadata = $Metadata
            RecoveryAttempts = 0
            RecoverySuccessful = $false
            FatalError = $FatalError
        }
        
        # Log the error
        Write-EnhancedLog "ERROR in context '$Context': $($ErrorRecord.Exception.Message)" "ERROR" "ErrorHandler" -Metadata $Metadata
        Write-EnhancedLog "Error type: $($errorInfo.ErrorType)" "ERROR" "ErrorHandler"
        Write-EnhancedLog "Command: $($errorInfo.Command) at line $($errorInfo.Line)" "ERROR" "ErrorHandler"
        Write-EnhancedLog "Stack trace: $($errorInfo.StackTrace)" "DEBUG" "ErrorHandler"
        
        # Attempt recovery actions
        if ($RecoveryActions.Count -gt 0 -and -not $FatalError) {
            Write-EnhancedLog "Attempting recovery actions..." "INFO" "ErrorHandler"
            
            foreach ($recoveryAction in $RecoveryActions) {
                try {
                    $errorInfo.RecoveryAttempts++
                    Write-EnhancedLog "Recovery attempt $($errorInfo.RecoveryAttempts)" "INFO" "ErrorHandler"
                    
                    $recoveryResult = & $recoveryAction -ErrorInfo $errorInfo
                    
                    if ($recoveryResult.Success) {
                        $errorInfo.RecoverySuccessful = $true
                        Write-EnhancedLog "Recovery successful: $($recoveryResult.Message)" "SUCCESS" "ErrorHandler"
                        break
                    } else {
                        Write-EnhancedLog "Recovery failed: $($recoveryResult.Message)" "WARN" "ErrorHandler"
                    }
                    
                } catch {
                    Write-EnhancedLog "Recovery action failed: $($_.Exception.Message)" "ERROR" "ErrorHandler"
                }
            }
        }
        
        # Store error in global error collection
        $script:errorHistory = @($script:errorHistory) + $errorInfo
        
        # Handle fatal errors
        if ($FatalError) {
            Write-EnhancedLog "FATAL ERROR: Terminating execution" "ERROR" "ErrorHandler"
            Write-FatalErrorReport -ErrorInfo $errorInfo
            exit 1
        }
        
        return $errorInfo
        
    } catch {
        Write-EnhancedLog "Error in error handling: $($_.Exception.Message)" "ERROR" "ErrorHandler"
        throw
    }
}

function Try-CatchBlock {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [scriptblock]$ScriptBlock,
        
        [Parameter(Mandatory=$false)]
        [string]$Context = "Unknown",
        
        [Parameter(Mandatory=$false)]
        [scriptblock[]]$RecoveryActions = @(),
        
        [Parameter(Mandatory=$false)]
        [hashtable]$Metadata = @(),
        
        [Parameter(Mandatory=$false)]
        [switch]$ContinueOnError,
        
        [Parameter(Mandatory=$false)]
        [scriptblock]$FinallyBlock
    )
    
    try {
        Write-EnhancedLog "Executing script block in context: $Context" "INFO" "ErrorHandler"
        
        $result = & $ScriptBlock
        
        Write-EnhancedLog "Script block completed successfully in context: $Context" "SUCCESS" "ErrorHandler"
        return $result
        
    } catch {
        $errorInfo = Invoke-ErrorHandling -ErrorRecord $_ -Context $Context -RecoveryActions $RecoveryActions -Metadata $Metadata
        
        if (-not $ContinueOnError) {
            throw $_
        } else {
            Write-EnhancedLog "Continuing execution after error in context: $Context" "WARN" "ErrorHandler"
            return $null
        }
    } finally {
        if ($FinallyBlock) {
            try {
                Write-EnhancedLog "Executing finally block for context: $Context" "INFO" "ErrorHandler"
                & $FinallyBlock
            } catch {
                Write-EnhancedLog "Error in finally block: $($_.Exception.Message)" "ERROR" "ErrorHandler"
            }
        }
    }
}

function Write-FatalErrorReport {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$ErrorInfo
    )
    
    try {
        $reportPath = "logs/fatal/FatalError_$(Get-Date -Format 'yyyyMMdd_HHmmss').json"
        
        # Ensure directory exists
        $reportDir = Split-Path $reportPath -Parent
        if (-not (Test-Path $reportDir)) {
            New-Item -Path $reportDir -ItemType Directory -Force | Out-Null
        }
        
        # Create detailed report
        $report = @{
            ReportType = "FatalError"
            Timestamp = $ErrorInfo.Timestamp
            Context = $ErrorInfo.Context
            ErrorMessage = $ErrorInfo.ErrorMessage
            ErrorType = $ErrorInfo.ErrorType
            Command = $ErrorInfo.Command
            Line = $ErrorInfo.Line
            Position = $ErrorInfo.Position
            StackTrace = $ErrorInfo.StackTrace
            Metadata = $ErrorInfo.Metadata
            RecoveryAttempts = $ErrorInfo.RecoveryAttempts
            RecoverySuccessful = $ErrorInfo.RecoverySuccessful
            SystemInfo = Get-SystemInfo
            Environment = Get-EnvironmentInfo
            ErrorHistory = $script:errorHistory
        }
        
        # Write report
        $reportJson = $report | ConvertTo-Json -Depth 10
        $reportJson | Out-File -FilePath $reportPath -Encoding UTF8
        
        Write-EnhancedLog "Fatal error report written to: $reportPath" "INFO" "ErrorHandler"
        
    } catch {
        Write-EnhancedLog "Failed to write fatal error report: $($_.Exception.Message)" "ERROR" "ErrorHandler"
    }
}

function Get-SystemInfo {
    try {
        return [PSCustomObject]@{
            ComputerName = $env:COMPUTERNAME
            OSVersion = (Get-WmiObject -Class Win32_OperatingSystem).Caption
            OSBuild = (Get-WmiObject -Class Win32_OperatingSystem).BuildNumber
            PowerShellVersion = $PSVersionTable.PSVersion.ToString()
            TotalRAM = [math]::Round((Get-WmiObject -Class Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2)
            CPUCores = (Get-WmiObject -Class Win32_Processor).NumberOfCores
            CurrentUser = $env:USERNAME
            ProcessID = $PID
            StartTime = Get-Process -Id $PID | Select-Object -ExpandProperty StartTime
        }
    } catch {
        Write-EnhancedLog "Error getting system info: $($_.Exception.Message)" "ERROR" "ErrorHandler"
        return [PSCustomObject]@{ Error = $_.Exception.Message }
    }
}

function Get-EnvironmentInfo {
    try {
        return [PSCustomObject]@{
            Path = $env:PATH
            Temp = $env:TEMP
            UserProfile = $env:USERPROFILE
            WorkingDirectory = (Get-Location).Path
            ScriptRoot = $PSScriptRoot
            ExecutionPolicy = Get-ExecutionPolicy
            Modules = (Get-Module).Count
            SnapIns = (Get-PSSnapin).Count
            NetworkInterfaces = Get-NetAdapter | Where-Object { $_.Status -eq 'Up' } | Select-Object -ExpandProperty Name
        }
    } catch {
        Write-EnhancedLog "Error getting environment info: $($_.Exception.Message)" "ERROR" "ErrorHandler"
        return [PSCustomObject]@{ Error = $_.Exception.Message }
    }
}

function Clear-ErrorHistory {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [int]$KeepLast = 100
    )
    
    try {
        if ($script:errorHistory.Count -gt $KeepLast) {
            $script:errorHistory = $script:errorHistory | Select-Object -Last $KeepLast
            Write-EnhancedLog "Error history cleared, keeping last $KeepLast entries" "INFO" "ErrorHandler"
        }
    } catch {
        Write-EnhancedLog "Error clearing error history: $($_.Exception.Message)" "ERROR" "ErrorHandler"
    }
}

function Get-ErrorStatistics {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [datetime]$Since = (Get-Date).AddHours(-24)
    )
    
    try {
        if (-not $script:errorHistory) {
            return [PSCustomObject]@{
                TotalErrors = 0
                ErrorsByType = @{}
                ErrorsByContext = @{}
                ErrorsByHour = @{}
                MostCommonError = $null
                RecoverySuccessRate = 0
            }
        }
        
        $recentErrors = $script:errorHistory | Where-Object { $_.Timestamp -ge $Since }
        
        $errorsByType = @{}
        $errorsByContext = @{}
        $errorsByHour = @{}
        $recoveryAttempts = 0
        $recoverySuccesses = 0
        
        foreach ($error in $recentErrors) {
            # Count by type
            $errorsByType[$error.ErrorType] = ($errorsByType[$error.ErrorType] + 1)
            
            # Count by context
            $errorsByContext[$error.Context] = ($errorsByContext[$error.Context] + 1)
            
            # Count by hour
            $hour = $error.Timestamp.Hour
            $errorsByHour[$hour] = ($errorsByHour[$hour] + 1)
            
            # Track recovery
            if ($error.RecoveryAttempts -gt 0) {
                $recoveryAttempts++
                if ($error.RecoverySuccessful) {
                    $recoverySuccesses++
                }
            }
        }
        
        # Find most common error
        $mostCommonError = if ($errorsByType.Keys.Count -gt 0) {
            $errorsByType.GetEnumerator() | Sort-Object -Property Value -Descending | Select-Object -First 1
        } else { $null }
        
        $recoveryRate = if ($recoveryAttempts -gt 0) {
            [math]::Round(($recoverySuccesses / $recoveryAttempts) * 100, 2)
        } else { 0 }
        
        return [PSCustomObject]@{
            TotalErrors = $recentErrors.Count
            ErrorsByType = $errorsByType
            ErrorsByContext = $errorsByContext
            ErrorsByHour = $errorsByHour
            MostCommonError = $mostCommonError
            RecoverySuccessRate = $recoveryRate
            TimeRange = "Since $Since"
        }
        
    } catch {
        Write-EnhancedLog "Error getting error statistics: $($_.Exception.Message)" "ERROR" "ErrorHandler"
        return [PSCustomObject]@{ Error = $_.Exception.Message }
    }
}

function New-RecoveryAction {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [scriptblock]$Action,
        
        [Parameter(Mandatory=$true)]
        [string]$Name,
        
        [Parameter(Mandatory=$false)]
        [int]$MaxAttempts = 3,
        
        [Parameter(Mandatory=$false)]
        [int]$DelaySeconds = 5,
        
        [Parameter(Mandatory=$false)]
        [scriptblock]$SuccessCondition = { $true }
    )
    
    return {
        param([object]$ErrorInfo)
        
        try {
            Write-EnhancedLog "Recovery action: $Name" "INFO" "ErrorHandler"
            
            $attempt = 0
            $success = $false
            
            while ($attempt -lt $MaxAttempts -and -not $success) {
                $attempt++
                
                try {
                    $result = & $Action -ErrorInfo $ErrorInfo
                    
                    if (& $SuccessCondition $result) {
                        $success = $true
                        return [PSCustomObject]@{
                            Success = $true
                            Message = "Recovery successful after $attempt attempt(s)"
                            Attempts = $attempt
                            Result = $result
                        }
                    }
                    
                } catch {
                    Write-EnhancedLog "Recovery action attempt $attempt failed: $($_.Exception.Message)" "WARN" "ErrorHandler"
                }
                
                if ($attempt -lt $MaxAttempts -and -not $success) {
                    Write-EnhancedLog "Waiting $DelaySeconds seconds before retry..." "INFO" "ErrorHandler"
                    Start-Sleep -Seconds $DelaySeconds
                }
            }
            
            return [PSCustomObject]@{
                Success = $false
                Message = "Recovery failed after $MaxAttempts attempt(s)"
                Attempts = $attempt
            }
            
        } catch {
            return [PSCustomObject]@{
                Success = $false
                Message = "Recovery action error: $($_.Exception.Message)"
                Attempts = $attempt
            }
        }
    }
}

# Initialize error history
$script:errorHistory = @()

# Export functions if this file is imported as a module
Export-ModuleMember -Function Invoke-ErrorHandling, Try-CatchBlock, Write-FatalErrorReport, Get-SystemInfo, Get-EnvironmentInfo, Clear-ErrorHistory, Get-ErrorStatistics, New-RecoveryAction
