<#
.SYNOPSIS
    Enhanced centralized logging framework for vSphere OneView automation suite.
.DESCRIPTION
    Provides standardized logging with multiple output formats, colors, and structured data support.
.PARAMETER Message
    Log message to be written
.PARAMETER Level
    Log level: DEBUG, INFO, WARN, ERROR, SUCCESS
.PARAMETER Component
    Component name generating the log entry
.PARAMETER LogFile
    Path to log file for persistent logging
.PARAMETER PassThru
    Return the log entry instead of just writing
.PARAMETER Metadata
    Additional metadata to include in structured logs
.EXAMPLE
    Write-EnhancedLog "Operation completed" "SUCCESS" "ComponentName"
.EXAMPLE
    Write-EnhancedLog "Error occurred" "ERROR" "ComponentName" -Metadata @{Host="esxi-01"; Error="Timeout"}
.NOTES
    File Name      : Logger.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

function Write-EnhancedLog {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$Message,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("DEBUG", "INFO", "WARN", "ERROR", "SUCCESS")]
        [string]$Level = "INFO",
        
        [Parameter(Mandatory=$false)]
        [string]$Component = "Unknown",
        
        [Parameter(Mandatory=$false)]
        [string]$LogFile = $global:LogFile,
        
        [Parameter(Mandatory=$false)]
        [switch]$PassThru,
        
        [Parameter(Mandatory=$false)]
        [hashtable]$Metadata = @{}
    )
    
    # Create timestamp
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss.fff"
    $level = $Level.PadRight(7)
    
    # Console message with colors
    $consoleEntry = "$timestamp [$level] [$Component] $Message"
    $colors = @{
        DEBUG = "Gray"
        INFO = "White"
        WARN = "Yellow"
        ERROR = "Red"
        SUCCESS = "Green"
    }
    
    # Write to console with appropriate color
    if ($colors.ContainsKey($Level)) {
        Write-Host $consoleEntry -ForegroundColor $colors[$Level]
    } else {
        Write-Host $consoleEntry
    }
    
    # Structured logging to file
    if ($LogFile) {
        try {
            # Ensure log directory exists
            $logDir = Split-Path $LogFile -Parent
            if (-not (Test-Path $logDir)) {
                New-Item -Path $logDir -ItemType Directory -Force | Out-Null
            }
            
            # Create log object
            $logObject = @{
                timestamp = $timestamp
                level = $Level
                component = $Component
                message = $Message
                metadata = $Metadata
                pid = $PID
                computer = $env:COMPUTERNAME
                user = $env:USERNAME
            }
            
            # Convert to JSON and append to file
            $logJson = $logObject | ConvertTo-Json -Compress
            Add-Content -Path $LogFile -Value $logJson -ErrorAction SilentlyContinue
            
        } catch {
            # Fallback logging if structured logging fails
            $fallbackEntry = "$timestamp [$Level] [$Component] $Message [LOGGING_ERROR: $($_.Exception.Message)]"
            try {
                Add-Content -Path $LogFile -Value $fallbackEntry -ErrorAction SilentlyContinue
            } catch {
                # Last resort - write to console only
                Write-Host "LOGGING SYSTEM ERROR: Unable to write to log file" -ForegroundColor Red
            }
        }
    }
    
    # Pass through if requested
    if ($PassThru) {
        return $consoleEntry
    }
}

<#
.SYNOPSIS
    Writes a separator line in logs.
.DESCRIPTION
    Creates visual separation in log files with customizable characters and length.
.PARAMETER Character
    Character to use for separator
.PARAMETER Length
    Length of separator line
.PARAMETER Level
    Log level to use
.PARAMETER Component
    Component name
.EXAMPLE
    Write-LogSeparator "=" 80 "SUCCESS" "Component"
#>

function Write-LogSeparator {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [string]$Character = "=",
        
        [Parameter(Mandatory=$false)]
        [int]$Length = 80,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("DEBUG", "INFO", "WARN", "ERROR", "SUCCESS")]
        [string]$Level = "INFO",
        
        [Parameter(Mandatory=$false)]
        [string]$Component = "Unknown"
    )
    
    $separator = $Character * $Length
    Write-EnhancedLog $separator $Level $Component
}

<#
.SYNOPSIS
    Creates a log file header with session information.
.DESCRIPTION
    Writes session information and configuration to the beginning of a log file.
.PARAMETER LogFile
    Path to log file
.PARAMETER SessionInfo
    Session information hashtable
.PARAMETER Config
    Configuration object
.EXAMPLE
    New-LogHeader -LogFile "session.log" -SessionInfo $sessionInfo -Config $config
#>

function New-LogHeader {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$LogFile,
        
        [Parameter(Mandatory=$false)]
        [hashtable]$SessionInfo = @{},
        
        [Parameter(Mandatory=$false)]
        [object]$Config = $null
    )
    
    # Clear existing log file if it exists
    if (Test-Path $LogFile) {
        Remove-Item $LogFile -Force
    }
    
    Write-EnhancedLog "=== VSPHERE ONEVIEW AUTOMATION SESSION ===" "SUCCESS" "Logger"
    Write-EnhancedLog "Session started: $(Get-Date)" "INFO" "Logger"
    Write-EnhancedLog "PowerShell version: $($PSVersionTable.PSVersion)" "INFO" "Logger"
    Write-EnhancedLog "Computer: $env:COMPUTERNAME" "INFO" "Logger"
    Write-EnhancedLog "User: $env:USERNAME" "INFO" "Logger"
    
    if ($Config) {
        Write-EnhancedLog "Configuration loaded from: $($Config.configFile)" "INFO" "Logger"
        Write-EnhancedLog "Environment: $($Config.system.environment)" "INFO" "Logger"
        Write-EnhancedLog "Simulation mode: $($Config.system.simulationMode)" "INFO" "Logger"
    }
    
    foreach ($key in $SessionInfo.Keys) {
        Write-EnhancedLog "Session $key`: $($SessionInfo[$key])" "INFO" "Logger"
    }
    
    Write-LogSeparator "=" 80 "INFO" "Logger"
}

<#
.SYNOPSIS
    Gets statistics from a log file.
.DESCRIPTION
    Analyzes log file to provide statistics on different log levels and components.
.PARAMETER LogFile
    Path to log file
.PARAMETER Since
    Filter logs since this datetime
.EXAMPLE
    Get-LogStatistics -LogFile "session.log" -Since (Get-Date).AddHours(-1)
#>

function Get-LogStatistics {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$LogFile,
        
        [Parameter(Mandatory=$false)]
        [datetime]$Since = (Get-Date).AddDays(-1)
    )
    
    try {
        if (-not (Test-Path $LogFile)) {
            return [PSCustomObject]@{
                TotalEntries = 0
                ByLevel = @{}
                ByComponent = @{}
                TimeRange = "No log file found"
            }
        }
        
        $logLines = Get-Content $LogFile | Where-Object { $_ -match '"timestamp":"([^"]+)"' }
        $filteredLogs = $logLines | Where-Object { 
            $line = $_ | ConvertFrom-Json -ErrorAction SilentlyContinue
            if ($line) {
                $logTime = [datetime]::ParseExact($line.timestamp, "yyyy-MM-dd HH:mm:ss.fff", $null)
                return $logTime -ge $Since
            }
            return $false
        }
        
        $byLevel = @{}
        $byComponent = @{}
        
        foreach ($logLine in $filteredLogs) {
            $logObj = $logLine | ConvertFrom-Json -ErrorAction SilentlyContinue
            if ($logObj) {
                $byLevel[$logObj.level] = ($byLevel[$logObj.level] + 1)
                $byComponent[$logObj.component] = ($byComponent[$logObj.component] + 1)
            }
        }
        
        $timeRange = "Last {0:N0} entries" -f $filteredLogs.Count
        
        return [PSCustomObject]@{
            TotalEntries = $filteredLogs.Count
            ByLevel = $byLevel
            ByComponent = $byComponent
            TimeRange = $timeRange
        }
        
    } catch {
        Write-EnhancedLog "Error analyzing log file: $($_.Exception.Message)" "ERROR" "Logger"
        return [PSCustomObject]@{
            TotalEntries = 0
            ByLevel = @{}
            ByComponent = @{}
            TimeRange = "Error analyzing log file"
        }
    }
}

# Export functions if this file is imported as a module
Export-ModuleMember -Function Write-EnhancedLog, Write-LogSeparator, New-LogHeader, Get-LogStatistics
