<#
.SYNOPSIS
    Input validation and prerequisite checking framework for vSphere OneView automation suite.
.DESCRIPTION
    Provides comprehensive validation for scripts, parameters, and system requirements.
.PARAMETER ScriptName
    Name of the script being validated
.PARAMETER Parameters
    Hashtable of parameters to validate
.PARAMETER Config
    Configuration object for context
.EXAMPLE
    Test-ScriptPrerequisites -ScriptName "Discovery" -Config $config
.EXAMPLE
    Test-Parameters -Parameters $PSBoundParameters -Schema $parameterSchema
.NOTES
    File Name      : ValidationEngine.ps1
    Author         : Generated by Opencode
    Prerequisite   : PowerShell 5.1+
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

function Test-ScriptPrerequisites {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$false)]
        [string[]]$RequiredModules = @("VMware.VimAutomation.Core", "HPEOneView.Lib"),
        
        [Parameter(Mandatory=$false)]
        [string[]]$RequiredPowerShellVersion = @("5.1", "6.0", "7.0"),
        
        [Parameter(Mandatory=$false)]
        [string[]]$RequiredDotNetVersion = @("4.8"),
        
        [Parameter(Mandatory=$false)]
        [hashtable]$CustomPrerequisites = @{}
    )
    
    try {
        Write-EnhancedLog "Starting script prerequisite validation" "INFO" "ValidationEngine"
        
        $results = [PSCustomObject]@{
            ScriptName = "Prerequisites"
            IsValid = $true
            Errors = @()
            Warnings = @()
            Details = @{}
        }
        
        # Test PowerShell version
        Write-EnhancedLog "Checking PowerShell version..." "INFO" "ValidationEngine"
        $currentVersion = $PSVersionTable.PSVersion.ToString()
        $results.Details.PowerShellVersion = $currentVersion
        
        if ($currentVersion -notin $RequiredPowerShellVersion) {
            $results.IsValid = $false
            $results.Errors += "PowerShell version $currentVersion is not supported. Required: $($RequiredPowerShellVersion -join ', ')"
        } else {
            Write-EnhancedLog "PowerShell version check passed: $currentVersion" "SUCCESS" "ValidationEngine"
        }
        
        # Test .NET Framework version
        Write-EnhancedLog "Checking .NET Framework version..." "INFO" "ValidationEngine"
        $netVersion = [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
        $results.Details.DotNetVersion = $netVersion
        
        if (-not ($netVersion -match [string]::Join('|', $RequiredDotNetVersion))) {
            $results.Warnings += ".NET Framework version may not be optimal: $netVersion"
        } else {
            Write-EnhancedLog ".NET Framework version check passed: $netVersion" "SUCCESS" "ValidationEngine"
        }
        
        # Test required modules
        Write-EnhancedLog "Checking required PowerShell modules..." "INFO" "ValidationEngine"
        $missingModules = @()
        $availableModules = @()
        
        foreach ($module in $RequiredModules) {
            try {
                $moduleInfo = Get-Module -Name $module -ListAvailable -ErrorAction SilentlyContinue
                if ($moduleInfo) {
                    $availableModules += "$($moduleInfo.Name) v$($moduleInfo.Version)"
                    Write-EnhancedLog "Module available: $($moduleInfo.Name) v$($moduleInfo.Version)" "SUCCESS" "ValidationEngine"
                } else {
                    $missingModules += $module
                    Write-EnhancedLog "Module missing: $module" "WARN" "ValidationEngine"
                }
            } catch {
                $missingModules += $module
                Write-EnhancedLog "Error checking module $module`: $($_.Exception.Message)" "WARN" "ValidationEngine"
            }
        }
        
        $results.Details.AvailableModules = $availableModules
        $results.Details.MissingModules = $missingModules
        
        if ($missingModules.Count -gt 0) {
            $results.IsValid = $false
            $results.Errors += "Missing required modules: $($missingModules -join ', ')"
        } else {
            Write-EnhancedLog "All required modules are available" "SUCCESS" "ValidationEngine"
        }
        
        # Test network connectivity
        Write-EnhancedLog "Checking network connectivity..." "INFO" "ValidationEngine"
        $connectivityTargets = @(
            $Config.vCenter.server,
            $Config.oneView.appliance
        )
        
        $connectivityResults = Test-SystemConnectivity -Targets $connectivityTargets -Port 443
        $results.Details.Connectivity = $connectivityResults
        
        $failedConnections = $connectivityResults | Where-Object { -not $_.TcpTestSucceeded }
        if ($failedConnections.Count -gt 0) {
            $results.Warnings += "Network connectivity issues detected to: $($failedConnections.Target -join ', ')"
        } else {
            Write-EnhancedLog "Network connectivity check passed" "SUCCESS" "ValidationEngine"
        }
        
        # Test credential availability
        Write-EnhancedLog "Checking credential availability..." "INFO" "ValidationEngine"
        $credentialTargets = @(
            $Config.vCenter.credentialTarget,
            $Config.oneView.credentialTarget
        )
        
        $credentialResults = @()
        foreach ($target in $credentialTargets) {
            $isAvailable = Test-CredentialAvailability -TargetName $target
            $credentialResults += [PSCustomObject]@{
                Target = $target
                Available = $isAvailable
            }
            
            if ($isAvailable) {
                Write-EnhancedLog "Credential available: $target" "SUCCESS" "ValidationEngine"
            } else {
                Write-EnhancedLog "Credential not available: $target" "WARN" "ValidationEngine"
            }
        }
        
        $results.Details.Credentials = $credentialResults
        $missingCredentials = $credentialResults | Where-Object { -not $_.Available }
        
        if ($missingCredentials.Count -gt 0) {
            $results.IsValid = $false
            $results.Errors += "Missing credentials for: $($missingCredentials.Target -join ', ')"
        } else {
            Write-EnhancedLog "All required credentials are available" "SUCCESS" "ValidationEngine"
        }
        
        # Test configuration validity
        Write-EnhancedLog "Checking configuration validity..." "INFO" "ValidationEngine"
        $configValidation = Test-ConfigurationValidity -Config $Config
        
        if (-not $configValidation.IsValid) {
            $results.IsValid = $false
            $results.Errors += $configValidation.Errors
        } else {
            Write-EnhancedLog "Configuration validation passed" "SUCCESS" "ValidationEngine"
        }
        
        # Custom prerequisites
        foreach ($key in $CustomPrerequisites.Keys) {
            try {
                Write-EnhancedLog "Checking custom prerequisite: $key" "INFO" "ValidationEngine"
                $result = & $CustomPrerequisites[$key]
                $results.Details.$key = $result
                
                if ($result -is [bool] -and -not $result) {
                    $results.IsValid = $false
                    $results.Errors += "Custom prerequisite failed: $key"
                }
            } catch {
                $results.IsValid = $false
                $results.Errors += "Custom prerequisite error ($key): $($_.Exception.Message)"
            }
        }
        
        # Final result
        if ($results.IsValid) {
            Write-EnhancedLog "All script prerequisites passed" "SUCCESS" "ValidationEngine"
        } else {
            Write-EnhancedLog "Script prerequisites validation failed" "ERROR" "ValidationEngine"
            foreach ($error in $results.Errors) {
                Write-EnhancedLog "ERROR: $error" "ERROR" "ValidationEngine"
            }
        }
        
        foreach ($warning in $results.Warnings) {
            Write-EnhancedLog "WARNING: $warning" "WARN" "ValidationEngine"
        }
        
        return $results
        
    } catch {
        Write-EnhancedLog "Prerequisite validation error: $($_.Exception.Message)" "ERROR" "ValidationEngine"
        throw
    }
}

function Test-Parameters {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Parameters,
        
        [Parameter(Mandatory=$false)]
        [hashtable]$Schema = @{},
        
        [Parameter(Mandatory=$false)]
        [hashtable]$Validators = @{}
    )
    
    try {
        Write-EnhancedLog "Starting parameter validation" "INFO" "ValidationEngine"
        
        $results = [PSCustomObject]@{
            IsValid = $true
            Errors = @()
            Warnings = @()
            Details = @{}
        }
        
        foreach ($param in $Parameters.Keys) {
            $value = $Parameters[$param]
            $paramResult = [PSCustomObject]@{
                Parameter = $param
                Value = $value
                Valid = $true
                Messages = @()
            }
            
            # Schema validation
            if ($Schema.ContainsKey($param)) {
                $schemaRule = $Schema[$param]
                $schemaValidation = Test-ParameterSchema -Parameter $param -Value $value -Schema $schemaRule
                $paramResult.Valid = $schemaValidation.Valid
                $paramResult.Messages += $schemaValidation.Messages
            }
            
            # Custom validator
            if ($Validators.ContainsKey($param)) {
                $validatorResult = & $Validators[$param] $value
                if ($validatorResult -is [bool]) {
                    $paramResult.Valid = $paramResult.Valid -and $validatorResult
                    if (-not $validatorResult) {
                        $paramResult.Messages += "Custom validation failed"
                    }
                } elseif ($validatorResult -is [hashtable]) {
                    $paramResult.Valid = $paramResult.Valid -and $validatorResult.Valid
                    $paramResult.Messages += $validatorResult.Messages
                }
            }
            
            $results.Details.$param = $paramResult
            
            if ($paramResult.Valid) {
                Write-EnhancedLog "Parameter validation passed: $param" "SUCCESS" "ValidationEngine"
            } else {
                $results.IsValid = $false
                foreach ($message in $paramResult.Messages) {
                    $error = "Parameter '$param': $message"
                    $results.Errors += $error
                    Write-EnhancedLog $error "ERROR" "ValidationEngine"
                }
            }
        }
        
        return $results
        
    } catch {
        Write-EnhancedLog "Parameter validation error: $($_.Exception.Message)" "ERROR" "ValidationEngine"
        throw
    }
}

function Test-ParameterSchema {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$Parameter,
        
        [Parameter(Mandatory=$true)]
        [object]$Value,
        
        [Parameter(Mandatory=$true)]
        [hashtable]$Schema
    )
    
    try {
        $result = [PSCustomObject]@{
            Valid = $true
            Messages = @()
        }
        
        # Type validation
        if ($Schema.ContainsKey('Type')) {
            $expectedType = $Schema.Type
            if ($expectedType -eq 'string' -and $Value -isnot [string]) {
                $result.Valid = $false
                $result.Messages += "Expected string, got $($Value.GetType().Name)"
            } elseif ($expectedType -eq 'int' -and $Value -isnot [int]) {
                $result.Valid = $false
                $result.Messages += "Expected integer, got $($Value.GetType().Name)"
            } elseif ($expectedType -eq 'bool' -and $Value -isnot [bool]) {
                $result.Valid = $false
                $result.Messages += "Expected boolean, got $($Value.GetType().Name)"
            }
        }
        
        # Required validation
        if ($Schema.ContainsKey('Required') -and $Schema.Required -and ($null -eq $Value -or $Value -eq '')) {
            $result.Valid = $false
            $result.Messages += "Parameter is required but not provided"
        }
        
        # Minimum/Maximum validation
        if ($Schema.ContainsKey('Min') -and $Value -lt $Schema.Min) {
            $result.Valid = $false
            $result.Messages += "Value must be at least $($Schema.Min)"
        }
        
        if ($Schema.ContainsKey('Max') -and $Value -gt $Schema.Max) {
            $result.Valid = $false
            $result.Messages += "Value must be at most $($Schema.Max)"
        }
        
        # Enum validation
        if ($Schema.ContainsKey('Enum')) {
            if ($Value -notin $Schema.Enum) {
                $result.Valid = $false
                $result.Messages += "Value must be one of: $($Schema.Enum -join ', ')"
            }
        }
        
        # Pattern validation (regex)
        if ($Schema.ContainsKey('Pattern') -and $Value -is [string]) {
            if ($Value -notmatch $Schema.Pattern) {
                $result.Valid = $false
                $result.Messages += "Value does not match required pattern"
            }
        }
        
        # Custom validation
        if ($Schema.ContainsKey('Validator') -and $Schema.Validator -is [scriptblock]) {
            $customResult = & $Schema.Validator $Value
            if (-not $customResult) {
                $result.Valid = $false
                $result.Messages += "Custom validation failed"
            }
        }
        
        return $result
        
    } catch {
        return [PSCustomObject]@{
            Valid = $false
            Messages = @("Schema validation error: $($_.Exception.Message)")
        }
    }
}

function Test-EnvironmentCompatibility {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$false)]
        [hashtable]$Requirements = @{
            MinimumRAMGB = 4
            MinimumDiskSpaceGB = 10
            MinimumCPUCores = 2
            RequiredWindowsFeatures = @()
            RequiredWindowsServices = @()
            RequiredNetworkPorts = @(443, 22)
        }
    )
    
    try {
        Write-EnhancedLog "Starting environment compatibility check" "INFO" "ValidationEngine"
        
        $results = [PSCustomObject]@{
            IsValid = $true
            Errors = @()
            Warnings = @()
            Details = @{}
        }
        
        # Check RAM
        $totalRAM = [math]::Round((Get-WmiObject -Class Win32_ComputerSystem).TotalPhysicalMemory / 1GB, 2)
        $results.Details.TotalRAMGB = $totalRAM
        
        if ($totalRAM -lt $Requirements.MinimumRAMGB) {
            $results.IsValid = $false
            $results.Errors += "Insufficient RAM: ${totalRAM}GB (required: $($Requirements.MinimumRAMGB)GB)"
        } else {
            Write-EnhancedLog "RAM check passed: ${totalRAM}GB" "SUCCESS" "ValidationEngine"
        }
        
        # Check disk space
        $systemDrive = Get-WmiObject -Class Win32_LogicalDisk -Filter "DeviceID='C:'"
        $freeDiskSpace = [math]::Round($systemDrive.FreeSpace / 1GB, 2)
        $results.Details.FreeDiskSpaceGB = $freeDiskSpace
        
        if ($freeDiskSpace -lt $Requirements.MinimumDiskSpaceGB) {
            $results.IsValid = $false
            $results.Errors += "Insufficient disk space: ${freeDiskSpace}GB (required: $($Requirements.MinimumDiskSpaceGB)GB)"
        } else {
            Write-EnhancedLog "Disk space check passed: ${freeDiskSpace}GB" "SUCCESS" "ValidationEngine"
        }
        
        # Check CPU cores
        $cpuCores = (Get-WmiObject -Class Win32_Processor).NumberOfCores
        $results.Details.CPUCores = $cpuCores
        
        if ($cpuCores -lt $Requirements.MinimumCPUCores) {
            $results.Warnings += "CPU cores below recommendation: $cpuCores (recommended: $($Requirements.MinimumCPUCores))"
        } else {
            Write-EnhancedLog "CPU cores check passed: $cpuCores" "SUCCESS" "ValidationEngine"
        }
        
        # Check Windows features
        if ($Requirements.RequiredWindowsFeatures.Count -gt 0) {
            $installedFeatures = Get-WindowsFeature -ErrorAction SilentlyContinue
            $missingFeatures = $Requirements.RequiredWindowsFeatures | Where-Object { $_ -notin $installedFeatures.Name }
            
            if ($missingFeatures.Count -gt 0) {
                $results.IsValid = $false
                $results.Errors += "Missing Windows features: $($missingFeatures -join ', ')"
            } else {
                Write-EnhancedLog "Windows features check passed" "SUCCESS" "ValidationEngine"
            }
        }
        
        # Check Windows services
        if ($Requirements.RequiredWindowsServices.Count -gt 0) {
            $services = Get-Service -ErrorAction SilentlyContinue
            $stoppedServices = $Requirements.RequiredWindowsServices | Where-Object { 
                $service = $services | Where-Object { $_.Name -eq $_ }
                return ($null -eq $service -or $service.Status -ne 'Running')
            }
            
            if ($stoppedServices.Count -gt 0) {
                $results.Warnings += "Required services not running: $($stoppedServices -join ', ')"
            } else {
                Write-EnhancedLog "Windows services check passed" "SUCCESS" "ValidationEngine"
            }
        }
        
        # Check network ports
        if ($Requirements.RequiredNetworkPorts.Count -gt 0) {
            $listeningPorts = Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | Select-Object -ExpandProperty LocalPort
            $closedPorts = $Requirements.RequiredNetworkPorts | Where-Object { $_ -notin $listeningPorts }
            
            # Note: This is a basic check - actual connectivity should be tested separately
            if ($closedPorts.Count -gt 0) {
                $results.Warnings += "Network ports not listening: $($closedPorts -join ', ')"
            }
        }
        
        return $results
        
    } catch {
        Write-EnhancedLog "Environment compatibility check error: $($_.Exception.Message)" "ERROR" "ValidationEngine"
        throw
    }
}

function Test-DataIntegrity {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$DataPath,
        
        [Parameter(Mandatory=$false)]
        [string]$ExpectedHash,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet("SHA256", "SHA512", "MD5")]
        [string]$HashAlgorithm = "SHA256"
        
    )
    
    try {
        Write-EnhancedLog "Starting data integrity check for: $DataPath" "INFO" "ValidationEngine"
        
        if (-not (Test-Path $DataPath)) {
            throw "File not found: $DataPath"
        }
        
        # Calculate file hash
        $hash = Get-FileHash -Path $DataPath -Algorithm $HashAlgorithm
        $actualHash = $hash.Hash
        
        $results = [PSCustomObject]@{
            FilePath = $DataPath
            HashAlgorithm = $HashAlgorithm
            ActualHash = $actualHash
            ExpectedHash = $ExpectedHash
            IsValid = $true
            Message = ""
        }
        
        if ($ExpectedHash -and $actualHash -ne $ExpectedHash) {
            $results.IsValid = $false
            $results.Message = "Hash mismatch. Expected: $ExpectedHash, Actual: $actualHash"
            Write-EnhancedLog $results.Message "ERROR" "ValidationEngine"
        } else {
            $results.Message = "Data integrity check passed"
            Write-EnhancedLog $results.Message "SUCCESS" "ValidationEngine"
        }
        
        return $results
        
    } catch {
        Write-EnhancedLog "Data integrity check error: $($_.Exception.Message)" "ERROR" "ValidationEngine"
        throw
    }
}

# Export functions if this file is imported as a module
Export-ModuleMember -Function Test-ScriptPrerequisites, Test-Parameters, Test-ParameterSchema, Test-EnvironmentCompatibility, Test-DataIntegrity
