<#
.SYNOPSIS
    OneView discovery automation with Serbian language.
.DESCRIPTION
    OneView otkrivanje sa srpskim jezikom i integracijom sa utility framework-om.
.PARAMETER Config
    Konfiguracioni objekat
.PARAMETER IncludeFirmwareInfo
    Uključi firmware informacije
.PARAMETER ExportResults
    Izvezi rezultate
.EXAMPLE
    Invoke-OneViewDiscovery -Config $config
.NOTES
    File Name      : 07_Discovery_OneView.ps1
    Author         : Generated by Opencode
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

# Import utility functions
. "$PSScriptRoot\..\05_Utility\ConnectionManager.ps1"
. "$PSScriptRoot\..\05_Utility\ErrorHandler.ps1"
. "$PSScriptRoot\..\05_Utility\Logger.ps1"
. "$PSScriptRoot\..\05_Utility\ConfigManager.ps1"

function Invoke-OneViewDiscovery {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$false)]
        [switch]$IncludeFirmwareInfo = $false,
        
        [Parameter(Mandatory=$false)]
        [switch]$ExportResults = $true
    )
    
    Try-CatchBlock -Context "OneView Discovery" -RecoveryActions @(
        (New-RecoveryAction -Action {
            param($ErrorInfo)
            Write-EnhancedLog "Pokušaj re-konekcije na OneView..." "INFO" "OneViewDiscovery"
            $connection = Connect-OneViewSafely -Appliance $Config.oneView.appliance -Credential (Get-StoredCredential -Target $Config.oneView.credentialTarget)
            return @{ Success = $true; Connection = $connection }
        } -Name "Reconnect-OneView" -MaxAttempts 3)
    ) -FinallyBlock {
        Disconnect-AllSafely
    } -ScriptBlock {
        
        Write-EnhancedLog "Povezivanje na OneView appliance: $($Config.oneView.appliance)" "INFO" "OneViewDiscovery"
        $connection = Connect-OneViewSafely -Appliance $Config.oneView.appliance -Credential (Get-StoredCredential -Target $Config.oneView.credentialTarget) -TestConnection
        
        $discoveryData = [PSCustomObject]@{
            Timestamp = Get-Date
            ApplianceName = $Config.oneView.appliance
            ServerHardware = @()
            ServerProfiles = @()
            Enclosures = @()
            LogicalInterconnects = @()
            Networks = @()
            StorageSystems = @()
            FirmwareBundles = @()
            Summary = @{}
        }
        
        # Discover server hardware
        $discoveryData.ServerHardware = Get-HPOVServerHardware | Select-Object Name, Model, Status, SerialNumber, ProcessorType, MemoryMB
        Write-EnhancedLog "Otkriveno server hardware: $($discoveryData.ServerHardware.Count) jedinica" "INFO" "OneViewDiscovery"
        
        # Discover server profiles
        $discoveryData.ServerProfiles = Get-HPOVServerProfile | Select-Object Name, Status, ServerHardware, ConnectionSettings
        Write-EnhancedLog "Otkriveno server profila: $($discoveryData.ServerProfiles.Count)" "INFO" "OneViewDiscovery"
        
        # Discover enclosures
        $discoveryData.Enclosures = Get-HPOVEnclosure | Select-Object Name, Model, Status, SerialNumber
        Write-EnhancedLog "Otkriveno enklouzura: $($discoveryData.Enclosures.Count)" "INFO" "OneViewDiscovery"
        
        # Create summary
        $discoveryData.Summary = [PSCustomObject]@{
            TotalServerHardware = $discoveryData.ServerHardware.Count
            TotalServerProfiles = $discoveryData.ServerProfiles.Count
            TotalEnclosures = $discoveryData.Enclosures.Count
            TotalLogicalInterconnects = $discoveryData.LogicalInterconnects.Count
            TotalNetworks = $discoveryData.Networks.Count
            TotalFirmwareBundles = $discoveryData.FirmwareBundles.Count
        }
        
        Write-EnhancedLog "OneView otkrivanje završeno uspešno" "SUCCESS" "OneViewDiscovery"
        
        return $discoveryData
    }
}

# Export funkcije
Export-ModuleMember -Function Invoke-OneViewDiscovery
