<#
.SYNOPSIS
    Automated infrastructure validation for vSphere OneView automation suite.
.DESCRIPTION
    Validacija infrastrukture sa srpskim jezikom i integracijom sa utility framework-om.
.PARAMETER Config
    Konfiguracioni objekat
.PARAMETER SkipNetworkTests
    Preskoči network testove
.PARAMETER GenerateReport
    Generiši izveštaj
.EXAMPLE
    Invoke-InfrastructureValidation -Config $config
.NOTES
    File Name      : 04_Infra_Validate.ps1
    Author         : Generated by Opencode
    Version        : 1.0.0
    Last Updated   : 2026-02-01
#>

# Import utility functions
. "$PSScriptRoot\..\05_Utility\ValidationEngine.ps1"
. "$PSScriptRoot\..\05_Utility\ConfigManager.ps1"
. "$PSScriptRoot\..\05_Utility\ConnectionManager.ps1"
. "$PSScriptRoot\..\05_Utility\ErrorHandler.ps1"
. "$PSScriptRoot\..\05_Utility\Logger.ps1"

function Invoke-InfrastructureValidation {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [object]$Config,
        
        [Parameter(Mandatory=$false)]
        [switch]$SkipNetworkTests = $false,
        
        [Parameter(Mandatory=$false)]
        [switch]$GenerateReport = $true
    )
    
    try {
        Write-EnhancedLog "Pokretanje provere infrastrukture..." "INFO" "InfraValidate"
        
        # Integracija sa ValidationEngine
        $prereqResult = Test-ScriptPrerequisites -Config $Config -RequiredModules @("VMware.VimAutomation.Core", "HPEOneView.Lib")
        if (-not $prereqResult.IsValid) {
            throw "Preduslovi nisu ispunjeni: $($prereqResult.Errors -join ', ')"
        }
        
        # Environment compatibility check
        $envResult = Test-EnvironmentCompatibility -Requirements @{
            MinimumRAMGB = 8
            MinimumDiskSpaceGB = 50
            MinimumCPUCores = 4
            RequiredNetworkPorts = @(443, 22, 161)
        }
        
        # Network connectivity validation
        if (-not $SkipNetworkTests) {
            $connectivityTargets = @(
                $Config.vCenter.server,
                $Config.oneView.appliance,
                "vcsa.domain.com",
                "composer.domain.com"
            )
            $networkResult = Test-SystemConnectivity -Targets $connectivityTargets -Port 443
        }
        
        # Generiši comprehensive report
        $validationReport = [PSCustomObject]@{
            Timestamp = Get-Date
            Prerequisites = $prereqResult
            Environment = $envResult
            NetworkConnectivity = $networkResult
            OverallStatus = if ($prereqResult.IsValid -and $envResult.IsValid) { "PASS" } else { "FAIL" }
            Recommendations = @()
        }
        
        if ($GenerateReport) {
            $reportPath = "reports/infra-validation-$(Get-Date -Format 'yyyyMMdd-HHmmss').json"
            Export-Configuration -Config $validationReport -OutputFile $reportPath -Pretty
            Write-EnhancedLog "Izveštaj sačuvan: $reportPath" "SUCCESS" "InfraValidate"
        }
        
        return $validationReport
        
    } catch {
        $errorInfo = Invoke-ErrorHandling -ErrorRecord $_ -Context "Infrastrukturna validacija" -FatalError
        throw
    }
}

# Export funkcije
Export-ModuleMember -Function Invoke-InfrastructureValidation
