# -*- coding: utf-8 -*-
"""
Modular keyword exports for subject detection.
"""

from .natural import SUBJECT_KEYWORDS as NATURAL_KEYWORDS
from .medical import SUBJECT_KEYWORDS as MEDICAL_KEYWORDS
from .technical import SUBJECT_KEYWORDS as TECHNICAL_KEYWORDS
from .social import SUBJECT_KEYWORDS as SOCIAL_KEYWORDS
from .culture import SUBJECT_KEYWORDS as CULTURE_KEYWORDS

SUBJECT_KEYWORDS = {}
SUBJECT_KEYWORDS.update(NATURAL_KEYWORDS)
SUBJECT_KEYWORDS.update(MEDICAL_KEYWORDS)
SUBJECT_KEYWORDS.update(TECHNICAL_KEYWORDS)
SUBJECT_KEYWORDS.update(SOCIAL_KEYWORDS)
SUBJECT_KEYWORDS.update(CULTURE_KEYWORDS)

__all__ = [
    "SUBJECT_KEYWORDS",
    "NATURAL_KEYWORDS",
    "MEDICAL_KEYWORDS",
    "TECHNICAL_KEYWORDS",
    "SOCIAL_KEYWORDS",
    "CULTURE_KEYWORDS",
]