# -*- coding: utf-8 -*-
"""
Keywords for MEDICAL SCIENCES (Medicinske nauke)
"""

SUBJECT_KEYWORDS = {
    "medicina": [
        "medicine", "medical", "disease", "symptom", "diagnosis", "therapy",
        "drug", "patient", "clinical", "health", "examination", "treatment",
        "dosage", "side effect", "contraindication", "vitamin", "hospital",
        "doctor", "physician", "specialist", "clinic",
        "medicina", "bolest", "simptom", "dijagnoza", "terapija", "lek",
        "pacijent", "klinički", "zdravlje", "pregled", "doziranje", "nuspojava",
        "contrainodiacija", "vitamin", "bolnica", "doktor", "lekar",
    ],
    "anatomija": [
        "anatomy", "anatomical", "body", "organ", "bone", "muscle", "joint",
        "spine", "skull", "chest", "abdomen", "pelvis", "extremity", "tissue",
        "anatomija", "anatomski", "telo", "organ", "kost", "mišić", "zglob",
        "kičma", "lobanja", "grudni koš", "trbuh", "zdjelica", "ekstremitet",
    ],
    "fiziologija": [
        "physiology", "physiological", "function", "respiration", "digestion",
        "circulation", "excretion", "reproduction", "nervous", "endocrine",
        "immune", "metabolism", "homeostasis",
        "fiziologija", "fiziološki", "funkcija", "disanje", "varenje",
        "cirkulacija", "ekskrecija", "reprodukcija", "nervni", "endokrini",
        "imuni", "metabolizam", "homeostaza",
    ],
    "farmakologija": [
        "pharmacology", "pharmacological", "drug", "dose", "effect", "side effect",
        "interaction", "contraindication", "indication", "oral", "intravenous",
        "intramuscular", "topical",
        "farmakologija", "farmakološki", "lek", "farmak", "doza", "dejstvo",
        "nuspojava", "interakcija", "contrainidkacija", "indikacija",
        "aplikacija", "oralno", "intravenozno", "intramuskularno", "topikalno",
    ],
    "patologija": [
        "patologija", "patološki", "bolest", "oboljenje", "promena", "upala",
        "nekroza", "hipertrofija", "atrofija", "hiplazija", "tumor", "karcinom",
        "benigni", "maligni", "metastaza",
    ],
    "hirurgija": [
        "surgery", "surgical", "operation", "surgeon", "scalpel", "anesthesia",
        "incision", "excision", "suture", "reconstruction", "transplantation",
        "laparoscopic", "endoscopic", "invasive", "minimally invasive",
        "hirurgija", "hirurški", "operacija", "hirurg", "skalpel", "anestezija",
        "incizija", "ekscizija", "sutra", "rekonstrukcija", "transplantacija",
    ],
    "psihijatrija": [
        "psychiatry", "psychiatric", "mental", "disorder", "diagnosis", "therapy",
        "treatment", "psychosis", "schizophrenia", "bipolar", "depression",
        "anxiety", "panic", "phobia",
        "psihijatrija", "psihijatrijski", "psihički", "poremećaj", "bolest",
        "dijagnoza", "terapija", "lečenje", "psihoza", "shizofrenija",
        "bipolarni", "depresija", "anksioznost", "panični", "fobije",
    ],
    "kardiologija": [
        "cardiology", "cardiologist", "heart", "cardiovascular", "circulation",
        "infarct", "angina", "arrhythmia", "hypertension", "hypotension",
        "failure", "valve", "coronary", "atherosclerosis",
        "kardiologija", "kardiolog", "srce", "kardiovaskularni", "cirkulacija",
        "infarkt", "angina", "aritmija", "hipertenzija", "hipotenzija", "zastoj",
        "insuficijencija", "valvula", "koronarna", "ateroskleroza",
    ],
    "onkologija": [
        "oncology", "oncologist", "tumor", "cancer", "malignant", "benign",
        "metastasis", "chemotherapy", "radiotherapy", "immunotherapy",
        "therapy", "prevention", "screening", "diagnostics", "prognosis",
        "onkologija", "onkolog", "tumor", "karcinom", "rak", "maligni",
        "benigni", "metastaza", "chemoterapija", "radioterapija", "imunoterapija",
    ],
    "neurologija": [
        "neurology", "neurologist", "brain", "nerve", "nervous system",
        "cerebral", "spinal", "meninges", "neuron", "synapse", "neurotransmitter",
        "stroke", "epilepsy", "migraine", "alzheimer", "parkinson",
        "neurologija", "neurolog", "mozak", "nerv", "nervni sistem", "cerebr",
        "spin", "meninge", "neuron", "sinapsa", "neurotransmiter", "moždani",
        "inсулт", "epilepsija", "migrena", "Alchajmer", "Parkinson",
    ],
    "ginekologija": [
        "gynecology", "gynecologist", "woman", "reproduction", "pregnancy",
        "childbirth", "menstrual", "hormones", "ovary", "uterus", "cervix",
        "contraception", "sterility", "fertility", "IVF",
        "ginekologija", "ginekolog", "žena", "reprodukcija", "trudnoća",
        "porođaj", "menstrualni", "hormoni", "jajnik", "materica", "grlić",
    ],
    "pedijatrija": [
        "pediatrics", "pediatrician", "child", "children", "newborn", "baby",
        "development", "growth", "immunization", "vaccination", "prevention",
        "disorder", "psychomotor", "speech", "walking", "developmental",
        "pedijatrija", "pedijatar", "dete", "dečiji", "novorođenče", "beba",
        "razvoj", "rast", "imunizacija", "vakcinacija",
    ],
    "dermatologija": [
        "dermatology", "dermatologist", "skin", "dermal", "dermatitis", "rash",
        "eczema", "psoriasis", "acne", "wart", "melanoma", "skin", "dermal",
        "subcutaneous", "infection", "fungal", "bacterial",
        "dermatologija", "dermatolog", "koža", "dermalni", "dermatit", "osip",
        "egzem", "psorijaza", "akne", "bradavica", "melanom", "kožni",
    ],
    "oftalmologija": [
        "ophthalmology", "ophthalmologist", "eye", "ocular", "vision", "visual",
        "retina", "cornea", "lens", "cataract", "glaucoma", "diopter", "glasses",
        "contact lens", "laser", "surgery",
        "oftalmologija", "oftalmolog", "oko", "očni", "vid", "vizuelni",
        "retina", "rožnjača", "sočivo", "beonjača", "glaukom", "katarakta",
    ],
    "otorinolaringologija": [
        "otorhinolaryngology", "ENT", "ear", "throat", "nose", "sinus", "hearing",
        "balance", "corti", "vestibular", "tonsil", "adenoid", "sinusitis",
        "otitis", "laryngitis", "pharyngitis", "rhinosinusitis",
        "otorinolaringologija", "orl", "uho", "grlo", "nos", "sinus", "sluh",
    ],
    "pneumoftiziologija": [
        "pneumophthisiology", "pulmonology", "lungs", "respiratory", "breathing",
        "bronch", "alveola", "pleura", "asthma", "bronchitis", "pneumonia",
        "tuberculosis", "COPD", "emphysema",
        "pneumoftiziologija", "pulmonologija", "pluća", "respiratorni", "disanje",
        "bronh", "alveola", "pleura", "astma", "bronhitis", "pneumonija",
    ],
    "gastroenterologija": [
        "gastroenterology", "gastroenterologist", "digestive", "system",
        "stomach", "intestine", "liver", "pancreas", "gallbladder", "gastritis",
        "ulcer", "hepatitis", "cirrhosis", "pancreatitis", "colitis",
        "gastroenterologija", "gastroenterolog", "digestivni", "želudac", "crevo",
        "jetra", "pankreas", "žuč", "gastritis", "čir", "hepatitis", "ciroza",
    ],
    "nefrologija": [
        "nephrology", "nephrologist", "kidney", "renal", "urinary", "dialysis",
        "transplantation", "glomerulonephritis", "pyelonephritis",
        "renal insufficiency", "hemodialysis", "peritoneal dialysis",
        "nefrologija", "nefrolog", "bubrezi", "renalni", "urinarni", "dijaliza",
        "transplantacija", "glomerulonefritis", "pielonefritis",
    ],
    "urologija": [
        "urology", "urologist", "urinary", "system", "bladder", "prostate",
        "renal", "ureter", "urethra", "hyperplasia", "stone", "infection",
        "incontinence", "tumor",
        "urologija", "urolog", "urinarni", "mokraćni", "bešika", "prostata",
    ],
    "reumatologija": [
        "reumatology", "reumatologist", "rheumatic", "joint", "muscle",
        "arthritis", "osteoarthritis", "rheumatoid", "artropathy", "spondylitis",
        "lupus", "scleroderma", "myositis", "fibromyalgia", "arthrosis",
        "reumatologija", "reumatolog", "reumatski", "zglob", "mišić", "artritis",
    ],
    "endokrinologija": [
        "endocrinology", "endocrinologist", "hormone", "gland", "endocrine",
        "thyroid", "parathyroid", "pituitary", "adrenal", "pancreas", "diabetes",
        "hyperthyroidism", "hypothyroidism", "cushing", "addison",
        "endokrinologija", "endokrinolog", "hormoni", "žlezda", "endokrini",
        "tiroid", "paratiroid", "hipofiza", "nadbubrežna", "dijabetes",
    ],
    "hematologija": [
        "hematology", "hematologist", "blood", "system", "erythrocyte",
        "leukocyte", "thrombocyte", "plasma", "serum", "anemia", "leukemia",
        "lymphoma", "hemophilia", "thrombosis",
        "hematologija", "hematolog", "krv", "krvni", "eritrociti", "leukociti",
        "trombociti", "plazma", "serum", "anemija", "leukemija", "limfom",
    ],
    "infektologija": [
        "infectology", "infectologist", "infection", "bacteria", "virus",
        "fungus", "parasite", "disease", "epidemic", "pandemic", "antibiotic",
        "antiviral", "immunity", "vaccine", "immunization",
        "infektologija", "infektolog", "infekcija", "bakterija", "virus",
        "gljivica", "parazit", "bolest", "zarazni", "epidemija", "pandemija",
    ],
}

__all__ = ["SUBJECT_KEYWORDS"]
